In [1]:
import pandas as pd

In [2]:
dataframe_original = pd.read_csv('watson_healthcare_modified.csv')
dataframe_original.head(10)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1313919,41,No,Travel_Rarely,1102,Cardiology,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,1200302,49,No,Travel_Frequently,279,Maternity,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,1060315,37,Yes,Travel_Rarely,1373,Maternity,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,1272912,33,No,Travel_Frequently,1392,Maternity,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,1414939,27,No,Travel_Rarely,591,Maternity,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
5,1633361,32,No,Travel_Frequently,1005,Maternity,2,2,Life Sciences,1,...,3,80,0,8,2,2,7,7,3,6
6,1329390,59,No,Travel_Rarely,1324,Maternity,3,3,Medical,1,...,1,80,3,12,3,2,1,0,0,0
7,1699288,30,No,Travel_Rarely,1358,Maternity,24,1,Life Sciences,1,...,2,80,1,1,2,3,1,0,0,0
8,1469740,38,No,Travel_Frequently,216,Maternity,23,3,Life Sciences,1,...,2,80,0,10,2,3,9,7,1,8
9,1101291,36,No,Travel_Rarely,1299,Maternity,27,3,Medical,1,...,2,80,2,17,3,2,7,7,7,7

In [3]:
(dataframe_original.columns)

Index(['EmployeeID', 'Age', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'Shift',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [7]:
df['WorkLifeBalance'].describe()

count    1676.000000
mean        2.766110
std         0.702369
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         4.000000
Name: WorkLifeBalance, dtype: float64

In [6]:
selected_columns = ['EmployeeID','Age','TotalWorkingYears','MonthlyIncome','OverTime',
                    'DistanceFromHome','YearsAtCompany','MonthlyRate',
                    'JobInvolvement','JobRole','JobLevel','YearsInCurrentRole',
                    'YearsSinceLastPromotion','YearsWithCurrManager',
                    'EnvironmentSatisfaction','Shift','WorkLifeBalance',
                    'PercentSalaryHike','MaritalStatus','Attrition']
df = dataframe_original[selected_columns]
df

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
0,1313919,41,8,5993,Yes,1,6,19479,3,Nurse,2,4,0,5,2,0,1,11,Single,No
1,1200302,49,10,5130,No,8,10,24907,2,Other,2,7,1,7,3,1,3,23,Married,No
2,1060315,37,7,2090,Yes,2,0,2396,2,Nurse,1,0,0,0,4,0,3,15,Single,Yes
3,1272912,33,8,2909,Yes,3,8,23159,3,Other,1,7,3,0,4,0,3,11,Married,No
4,1414939,27,6,3468,No,2,2,16632,3,Nurse,1,2,2,2,1,1,3,12,Married,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,1117656,26,1,2340,Yes,24,1,23213,1,Nurse,1,0,0,0,3,0,1,18,Single,Yes
1672,1152327,46,15,9071,Yes,10,3,11563,2,Nurse,3,2,1,2,3,1,3,19,Married,No
1673,1812428,20,1,2836,No,1,1,11757,2,Other,1,0,0,0,4,0,4,13,Single,No
1674,1812429,39,21,12742,No,1,21,7060,2,Therapist,4,6,11,8,4,1,3,16,Married,No
1675,1152329,27,9,6500,No,2,8,26997,4,Nurse,2,7,0,7,1,0,2,14,Single,No

In [8]:
df.to_csv('Feature_extracted_dataset(whd).csv', index=False)