In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Partially_cleaned_dataset.csv')
df.tail(6)

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
1670,1336016,28,0.250,0.063560,1,0.000000,0.175,0.071391,0.000000,1,0.00,0.388889,3,7,0.000000,0.000000,0.666667,0.142857,0,1
1671,1117656,26,0.025,0.070090,1,0.821429,0.025,0.847982,0.000000,1,0.00,0.000000,0,0,0.666667,0.000000,0.000000,0.500000,0,1
1672,1152327,46,0.375,0.424539,1,0.321429,0.075,0.380205,0.333333,1,0.50,0.111111,1,2,0.666667,0.333333,0.666667,0.571429,1,0
1673,1812428,20,0.025,0.096209,0,0.000000,0.025,0.387994,0.333333,0,0.00,0.000000,0,0,1.000000,0.000000,1.000000,0.142857,0,0
1674,1812429,39,0.525,0.617852,0,0.000000,0.525,0.199398,0.333333,2,0.75,0.333333,11,8,1.000000,0.333333,0.666667,0.357143,1,0
1675,1152329,27,0.225,0.289152,0,0.035714,0.200,0.999920,1.000000,1,0.25,0.388889,0,7,0.000000,0.000000,0.333333,0.214286,0,0

In [4]:
att_no = (df['Attrition'] == 0)
att_yes = (df['Attrition'] == 1)

In [5]:
print("Attrition(YES): ",att_yes.sum())
print("Attrition(NO) : ",att_no.sum())

Attrition(YES):  199
Attrition(NO) :  1477

In [6]:
df_no = df[df['Attrition'] == 0]
df_yes = df[df['Attrition'] == 1]

In [8]:
from sklearn.utils import resample

In [9]:
df_downsampled_no = resample(df_no, replace=False, n_samples=199, random_state=42)
df2 = pd.concat([df_downsampled_no, df_yes])

In [10]:
df2 = df2.sample(frac=1, random_state = 42).reset_index(drop=True)

In [12]:
print(f"Yes: {len(df2[df2['Attrition'] == 1])}, No: {len(df2[df2['Attrition'] == 0])}")
print(f"Total records: {len(df2)}")

Yes: 199, No: 199
Total records: 398

In [13]:
df2.sample(20)

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
299,1034220,30,0.175,0.059136,1,0.750000,0.125,0.379241,0.666667,0,0.00,0.111111,0,1,0.000000,0.000000,0.666667,0.000000,1,1
81,1827650,47,0.425,0.126962,0,0.000000,0.150,0.325678,0.666667,0,0.00,0.277778,1,2,0.000000,0.333333,0.333333,0.071429,1,0
111,1715239,53,0.550,0.728963,0,0.035714,0.425,0.475567,0.666667,3,0.75,0.722222,15,2,0.666667,0.333333,1.000000,0.142857,2,0
315,1179676,41,0.250,0.093154,1,0.035714,0.175,0.627625,0.000000,1,0.00,0.388889,1,0,0.333333,0.333333,0.333333,0.142857,2,1
48,1208054,32,0.225,0.271353,1,0.000000,0.225,0.352660,0.666667,2,0.25,0.444444,7,8,0.000000,0.333333,0.666667,0.785714,1,0
204,1148129,41,0.300,0.378094,1,0.285714,0.225,0.766995,0.666667,1,0.50,0.388889,0,7,0.666667,0.333333,0.666667,0.142857,2,0
58,1767733,42,0.600,0.479989,1,0.035714,0.500,0.663200,0.666667,0,0.50,0.444444,13,9,1.000000,0.333333,0.000000,0.214286,1,0
31,1293237,50,0.500,0.518431,1,0.964286,0.075,0.581891,0.333333,1,0.50,0.111111,2,0,1.000000,0.333333,0.666667,0.142857,2,1
297,1127107,32,0.100,0.143286,1,0.000000,0.075,0.300221,0.333333,1,0.00,0.111111,1,2,1.000000,0.000000,0.000000,0.214286,0,1
337,1095688,34,0.350,0.092628,0,0.035714,0.175,0.253845,0.333333,0,0.00,0.166667,5,7,1.000000,0.333333,0.666667,0.071429,2,0
193,1058169,50,0.075,0.088152,1,0.071429,0.075,0.068902,0.333333,0,0.00,0.111111,0,2,0.000000,0.000000,0.666667,0.214286,1,1
325,1340549,28,0.025,0.079305,1,0.392857,0.025,0.837623,0.666667,1,0.00,0.055556,0,0,0.666667,0.000000,0.333333,0.000000,1,1
169,1381585,35,0.125,0.062401,0,0.000000,0.075,0.151536,0.666667,0,0.00,0.111111,1,2,0.333333,0.333333,0.333333,0.142857,1,0
113,1704323,29,0.125,0.094313,1,0.000000,0.075,0.860389,0.333333,0,0.00,0.111111,0,2,0.333333,1.000000,0.666667,0.571429,2,1
374,1870106,58,0.075,0.072196,1,0.035714,0.025,0.453323,0.333333,1,0.00,0.000000,0,0,1.000000,0.333333,0.333333,0.214286,2,1
132,1542102,31,0.250,0.272249,1,0.750000,0.250,0.761413,0.666667,2,0.25,0.111111,6,7,1.000000,0.666667,0.333333,0.285714,1,1
393,1322097,30,0.250,0.225645,0,0.535714,0.175,0.282433,1.000000,1,0.25,0.000000,1,7,0.666667,0.333333,0.666667,0.357143,1,0
353,1549806,21,0.050,0.085097,0,0.321429,0.050,0.932102,0.333333,1,0.00,0.111111,2,2,0.000000,0.000000,0.000000,0.642857,0,1
232,1262683,22,0.025,0.101422,1,0.535714,0.025,0.209998,1.000000,1,0.00,0.000000,0,0,1.000000,0.666667,0.333333,0.142857,2,0
230,1265759,27,0.025,0.097630,0,0.750000,0.025,0.701104,0.333333,0,0.00,0.000000,0,0,0.000000,0.000000,0.666667,0.071429,1,1

In [16]:
df2.to_csv('Balanced_Set_Cross_Validation.csv')