In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('watson_healthcare_modified.csv')

In [43]:
df.head()

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1313919,41,No,Travel_Rarely,1102,Cardiology,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,1200302,49,No,Travel_Frequently,279,Maternity,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,1060315,37,Yes,Travel_Rarely,1373,Maternity,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,1272912,33,No,Travel_Frequently,1392,Maternity,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,1414939,27,No,Travel_Rarely,591,Maternity,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1676 entries, 0 to 1675
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeID                1676 non-null   int64
 1   Age                       1676 non-null   int64
 2   Attrition                 1676 non-null   object
 3   BusinessTravel            1676 non-null   object
 4   DailyRate                 1676 non-null   int64
 5   Department                1676 non-null   object
 6   DistanceFromHome          1676 non-null   int64
 7   Education                 1676 non-null   int64
 8   EducationField            1676 non-null   object
 9   EmployeeCount             1676 non-null   int64
 10  EnvironmentSatisfaction   1676 non-null   int64
 11  Gender                    1676 non-null   object
 12  HourlyRate                1676 non-null   int64
 13  JobInvolvement            1676 non-null   int64
 14  JobLevel                  1676 non-null   int64
 15  JobRole                   1676 non-null   object
 16  JobSatisfaction           1676 non-null   int64
 17  MaritalStatus             1676 non-null   object
 18  MonthlyIncome             1676 non-null   int64
 19  MonthlyRate               1676 non-null   int64
 20  NumCompaniesWorked        1676 non-null   int64
 21  Over18                    1676 non-null   object
 22  OverTime                  1676 non-null   object
 23  PercentSalaryHike         1676 non-null   int64
 24  PerformanceRating         1676 non-null   int64
 25  RelationshipSatisfaction  1676 non-null   int64
 26  StandardHours             1676 non-null   int64
 27  Shift                     1676 non-null   int64
 28  TotalWorkingYears         1676 non-null   int64
 29  TrainingTimesLastYear     1676 non-null   int64
 30  WorkLifeBalance           1676 non-null   int64
 31  YearsAtCompany            1676 non-null   int64
 32  YearsInCurrentRole        1676 non-null   int64
 33  YearsSinceLastPromotion   1676 non-null   int64
 34  YearsWithCurrManager      1676 non-null   int64
dtypes: int64(26), object(9)
memory usage: 458.4+ KB

In [45]:
X = df.drop(columns=['Attrition', 'EmployeeID', 'EmployeeCount', 'StandardHours', 'Over18'])
y = df['Attrition'].map({'Yes': 1, 'No': 0})

In [46]:
display(X.sample(5))
display(y.sample(5))

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
425,50,Travel_Rarely,1099,Neurology,29,4,Life Sciences,2,Male,88,...,3,2,1,28,2,3,27,10,15,7
437,35,Travel_Rarely,1276,Maternity,16,3,Life Sciences,4,Male,72,...,3,3,0,10,2,3,8,7,0,0
1279,33,Travel_Rarely,867,Maternity,8,4,Life Sciences,4,Male,90,...,3,2,1,14,1,3,10,8,7,6
108,25,Travel_Rarely,1280,Maternity,7,1,Medical,4,Male,64,...,3,3,2,2,2,3,2,2,2,1
1630,24,Travel_Frequently,535,Cardiology,24,3,Medical,4,Male,38,...,3,3,2,3,3,3,2,2,2,1

1079    0
72      0
511     1
108     0
937     1
Name: Attrition, dtype: int64

In [47]:
ohe_cols = ['Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']
ord_cols = ['BusinessTravel']

In [48]:
travel_rank = [['Non-Travel', 'Travel_Rarely', 'Travel_Frequently']]

In [49]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder

In [50]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat_ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False), ohe_cols),
        ('cat_ord', OrdinalEncoder(categories=travel_rank), ord_cols)
    ]
)

In [51]:
from sklearn.pipeline import Pipeline

In [52]:
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor)
])

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

In [55]:
X_train_encoded = pipeline.fit_transform(X_train)
X_test_encoded = pipeline.transform(X_test)

In [56]:
print(f"Encoded Data Shape: {X_train_encoded.shape}")

Encoded Data Shape: (1340, 22)