In [32]:
import pandas as pd

In [33]:
dataframe = pd.read_csv('watson_healthcare_modified.csv')
dataframe.sample(4)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
32,1874834,30,No,Travel_Rarely,125,Maternity,9,2,Medical,1,...,1,80,0,10,5,3,10,0,1,8
685,1612583,36,No,Travel_Rarely,938,Maternity,2,4,Medical,1,...,3,80,0,16,6,3,11,8,3,9
557,1808474,38,No,Travel_Rarely,268,Maternity,2,5,Medical,1,...,2,80,1,6,0,1,1,0,0,1
292,1794901,31,No,Travel_Frequently,444,Cardiology,5,3,Marketing,1,...,3,80,1,2,5,2,2,2,2,2

In [34]:
dataframe.shape

(1676, 35)

In [35]:
dataframe.select_dtypes(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,No,Travel_Rarely,Cardiology,Life Sciences,Female,Nurse,Single,Y,Yes
1,No,Travel_Frequently,Maternity,Life Sciences,Male,Other,Married,Y,No
2,Yes,Travel_Rarely,Maternity,Other,Male,Nurse,Single,Y,Yes
3,No,Travel_Frequently,Maternity,Life Sciences,Female,Other,Married,Y,Yes
4,No,Travel_Rarely,Maternity,Medical,Male,Nurse,Married,Y,No
...,...,...,...,...,...,...,...,...,...
1671,Yes,Travel_Rarely,Neurology,Technical Degree,Male,Nurse,Single,Y,Yes
1672,No,Travel_Rarely,Cardiology,Marketing,Female,Nurse,Married,Y,Yes
1673,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
1674,No,Travel_Rarely,Neurology,Life Sciences,Female,Therapist,Married,Y,No
1675,No,Travel_Rarely,Cardiology,Medical,Female,Nurse,Single,Y,No

In [36]:
dframe = dataframe.copy()
dframe.tail(5)
del dataframe # For original dataset safety

In [37]:
data = dframe.select_dtypes(include='int64')
data.columns

Index(['EmployeeID', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'Shift', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [38]:
df = dframe.select_dtypes(include='object')
display(df.shape)
df.sample(4)

(1676, 9)

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
539,No,Non-Travel,Maternity,Life Sciences,Female,Administrative,Married,Y,No
153,No,Travel_Rarely,Maternity,Life Sciences,Male,Nurse,Divorced,Y,No
1034,No,Travel_Rarely,Maternity,Technical Degree,Male,Therapist,Married,Y,Yes
897,No,Travel_Frequently,Maternity,Technical Degree,Male,Other,Married,Y,No

In [39]:
(dframe.dtypes).unique()

array([dtype('int64'), dtype('O')], dtype=object)

In [40]:
del dframe # Save memory

#### Dropping Over18 and EducationField

In [41]:
df.drop(columns=['Over18'], inplace=True)
df.sample(6)
display(df.shape)

(1676, 8)

In [42]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='error').set_output(transform='pandas')

### Encoding Objects to Numerical Values

#### Gender and Department encoding (ohe) and merging

In [44]:
enc_gender = ohe.fit_transform(df[['Gender']])
enc_department = ohe.fit_transform(df[['Department']])

In [45]:
enc_gender.sample(5)

      Gender_Female  Gender_Male
834             1.0          0.0
611             0.0          1.0
1403            0.0          1.0
6               1.0          0.0
680             1.0          0.0

In [46]:
enc_department.sample(4)

      Department_Cardiology  Department_Maternity  Department_Neurology
908                     1.0                   0.0                   0.0
1161                    0.0                   1.0                   0.0
270                     0.0                   0.0                   1.0
1622                    0.0                   1.0                   0.0

In [47]:
df = pd.concat([df, enc_department], axis=1).drop(columns=['Department'])
display(df.shape)
df.sample(5)

(1676, 10)

,Attrition,BusinessTravel,EducationField,Gender,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology
524,No,Travel_Rarely,Technical Degree,Female,Nurse,Single,No,0.0,1.0,0.0
424,No,Travel_Rarely,Marketing,Male,Administrative,Divorced,No,1.0,0.0,0.0
1425,No,Travel_Rarely,Life Sciences,Male,Other,Single,No,0.0,0.0,1.0
1296,No,Travel_Rarely,Life Sciences,Female,Nurse,Divorced,No,0.0,0.0,1.0
1115,No,Travel_Rarely,Life Sciences,Female,Other,Married,No,0.0,1.0,0.0

In [48]:
df = pd.concat([df, enc_gender], axis=1).drop(columns=['Gender'])
display(df.shape)
df.sample(7)

(1676, 11)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1421,No,Travel_Rarely,Medical,Nurse,Married,Yes,0.0,0.0,1.0,1.0,0.0
1201,No,Travel_Frequently,Medical,Other,Married,Yes,1.0,0.0,0.0,1.0,0.0
1641,No,Travel_Frequently,Medical,Nurse,Divorced,Yes,1.0,0.0,0.0,1.0,0.0
97,No,Non-Travel,Medical,Nurse,Married,No,1.0,0.0,0.0,0.0,1.0
1241,No,Travel_Frequently,Technical Degree,Other,Single,No,0.0,1.0,0.0,1.0,0.0
98,No,Travel_Rarely,Medical,Nurse,Single,No,1.0,0.0,0.0,0.0,1.0
342,No,Travel_Rarely,Medical,Therapist,Single,Yes,0.0,0.0,1.0,1.0,0.0

#### OverTime and Attrition encoding (mapping to 1s and 0s)

In [49]:
# yes = 1 | no = 0 
df['Attrition'] = df['Attrition'].map({'Yes': 1.0, 'No': 0.0})  
df['OverTime'] = df['OverTime'].map({'Yes': 1.0, 'No': 0.0})

In [50]:
df.head(3)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
0,0.0,Travel_Rarely,Life Sciences,Nurse,Single,1.0,1.0,0.0,0.0,1.0,0.0
1,0.0,Travel_Frequently,Life Sciences,Other,Married,0.0,0.0,1.0,0.0,0.0,1.0
2,1.0,Travel_Rarely,Other,Nurse,Single,1.0,0.0,1.0,0.0,0.0,1.0

#### Ordinal encoding for BusinessTravel and MaritalStatus

In [51]:
travel_frequency = ['Non-Travel', 'Travel_Rarely', 'Travel_Frequently'] # 0.0 = Non-Travel, 1.0 = Travel_Rarely, 2.0 = Travel_Frequently
marital_status = ['Single','Married', 'Divorced']

In [52]:
from sklearn.preprocessing import OrdinalEncoder

In [53]:
oe_travel = OrdinalEncoder(categories=[travel_frequency])
oe_marital_status = OrdinalEncoder(categories= [marital_status])

In [54]:
df['BusinessTravel'] = oe_travel.fit_transform(df[['BusinessTravel']])

In [55]:
df['MaritalStatus'] = oe_marital_status.fit_transform(df[['MaritalStatus']])

In [56]:
df.sample(10)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
998,0.0,1.0,Medical,Nurse,0.0,0.0,0.0,1.0,0.0,1.0,0.0
880,0.0,1.0,Medical,Other,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1510,0.0,1.0,Life Sciences,Nurse,2.0,0.0,0.0,0.0,1.0,0.0,1.0
42,1.0,1.0,Life Sciences,Nurse,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1045,0.0,1.0,Other,Nurse,0.0,0.0,1.0,0.0,0.0,0.0,1.0
287,0.0,1.0,Life Sciences,Nurse,2.0,0.0,0.0,1.0,0.0,0.0,1.0
1138,0.0,1.0,Medical,Other,1.0,0.0,0.0,1.0,0.0,0.0,1.0
868,1.0,1.0,Life Sciences,Nurse,1.0,0.0,0.0,1.0,0.0,1.0,0.0
1028,0.0,1.0,Marketing,Nurse,2.0,0.0,1.0,0.0,0.0,0.0,1.0
253,0.0,1.0,Life Sciences,Other,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [57]:
max_len = max(len(col) for col in df.columns) # finds the length of the largest column name

for col in df.columns:
    print(f'{col:<{max_len}} = {df[col].unique()}') # left aligns the column name

del max_len

Attrition             = [0. 1.]
BusinessTravel        = [1. 2. 0.]
EducationField        = ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
JobRole               = ['Nurse' 'Other' 'Therapist' 'Administrative' 'Admin']
MaritalStatus         = [0. 1. 2.]
OverTime              = [1. 0.]
Department_Cardiology = [1. 0.]
Department_Maternity  = [0. 1.]
Department_Neurology  = [0. 1.]
Gender_Female         = [1. 0.]
Gender_Male           = [0. 1.]

In [58]:
df[df['JobRole'] == 'Other'].count()

Attrition                534
BusinessTravel           534
EducationField           534
JobRole                  534
MaritalStatus            534
OverTime                 534
Department_Cardiology    534
Department_Maternity     534
Department_Neurology     534
Gender_Female            534
Gender_Male              534
dtype: int64

In [59]:
df[df['EducationField'] == 'Other'].count()

Attrition                88
BusinessTravel           88
EducationField           88
JobRole                  88
MaritalStatus            88
OverTime                 88
Department_Cardiology    88
Department_Maternity     88
Department_Neurology     88
Gender_Female            88
Gender_Male              88
dtype: int64

In [60]:
df.sample(7)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
824,0.0,2.0,Life Sciences,Other,2.0,1.0,0.0,1.0,0.0,0.0,1.0
1475,0.0,0.0,Technical Degree,Nurse,2.0,0.0,1.0,0.0,0.0,0.0,1.0
717,0.0,1.0,Life Sciences,Nurse,0.0,1.0,1.0,0.0,0.0,1.0,0.0
140,1.0,1.0,Medical,Nurse,0.0,0.0,0.0,1.0,0.0,1.0,0.0
18,0.0,1.0,Life Sciences,Administrative,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1643,0.0,1.0,Life Sciences,Nurse,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1227,0.0,1.0,Medical,Nurse,2.0,0.0,0.0,1.0,0.0,0.0,1.0

#### JobRole and EducationField encoding (categorical mapping)

In [61]:
df['EducationField'] = df['EducationField'].map({'Other': 0.0, 'Life Sciences': 1.0, 'Medical': 2.0, 'Marketing': 3.0, 'Technical Degree': 4.0, 'Human Resources': 5.0})
df['is_other_JobRole'] = (df['JobRole'] == 'Other').astype(float)
df['JobRole'] = df['JobRole'].map({'Other': 0.0, 'Nurse': 1.0,'Therapist': 2.0, 'Administrative': 3.0, 'Admin': 4.0})

In [62]:
display(df.shape)
df.sample(10)

(1676, 12)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole
208,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1030,0.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1394,0.0,2.0,1.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
107,1.0,1.0,3.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
657,0.0,1.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
370,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
833,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
985,0.0,2.0,1.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
399,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1152,0.0,1.0,2.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [63]:
df.isna().any()

Attrition                False
BusinessTravel           False
EducationField           False
JobRole                  False
MaritalStatus            False
OverTime                 False
Department_Cardiology    False
Department_Maternity     False
Department_Neurology     False
Gender_Female            False
Gender_Male              False
is_other_JobRole         False
dtype: bool

In [64]:
Object_df = df
del df # For Object data safety

### Scaling Numberical Values

In [65]:
print(f'Number of Columns: {len(data.columns)}')
data.columns

Number of Columns: 26

Index(['EmployeeID', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'Shift', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [66]:
max_len = max(len(col) for col in data.columns) 
for col in data.columns:
    print(f'{col:<{max_len}}: {data[col].nunique()}')

EmployeeID              : 1676
Age                     : 43
DailyRate               : 886
DistanceFromHome        : 29
Education               : 5
EmployeeCount           : 1
EnvironmentSatisfaction : 4
HourlyRate              : 71
JobInvolvement          : 4
JobLevel                : 5
JobSatisfaction         : 4
MonthlyIncome           : 1349
MonthlyRate             : 1427
NumCompaniesWorked      : 10
PercentSalaryHike       : 15
PerformanceRating       : 2
RelationshipSatisfaction: 4
StandardHours           : 1
Shift                   : 4
TotalWorkingYears       : 40
TrainingTimesLastYear   : 7
WorkLifeBalance         : 4
YearsAtCompany          : 37
YearsInCurrentRole      : 19
YearsSinceLastPromotion : 16
YearsWithCurrManager    : 18

In [67]:
data.columns[data.nunique() == 1]

Index(['EmployeeCount', 'StandardHours'], dtype='object')

In [68]:
print(data['EmployeeCount'].unique())
print(data['StandardHours'].unique())

[1]
[80]

In [69]:
data.shape

(1676, 26)

In [70]:
# dropping EmployeeCount and StandardHours due to lack of variety 
data.drop(['EmployeeCount', 'StandardHours'], axis=1, inplace=True)

In [71]:
data.shape

(1676, 24)

In [72]:
data.sample(4)

,EmployeeID,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1255,1498457,29,590,4,3,4,91,2,1,1,...,3,3,1,1,2,3,1,0,0,0
1345,1551391,40,1137,1,4,1,98,3,4,1,...,3,1,1,22,3,3,19,7,11,16
630,1341422,42,1271,2,1,2,35,3,1,4,...,3,4,0,8,2,3,2,1,2,2
1256,1322097,30,305,16,3,3,58,4,2,3,...,3,3,1,10,3,3,7,0,1,7

#### Dropping EmployeeID column

In [73]:
data.drop('EmployeeID', axis=1, inplace=True)
data.sample(4)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1032,31,1398,8,2,4,96,4,1,2,2109,...,3,4,0,8,3,3,3,2,0,2
765,40,300,26,3,3,74,3,2,1,8396,...,3,2,1,8,3,2,7,7,7,5
848,56,718,4,4,4,92,3,5,1,19943,...,3,4,1,28,2,3,5,2,4,2
1638,31,444,5,3,4,84,3,1,2,2789,...,3,3,1,2,5,2,2,2,2,2

In [74]:
for col in data.columns:
    if (data[col].nunique() < 7):
        print(f'{col:<{max_len}}: {data[col].unique()}')

Education               : [2 1 4 3 5]
EnvironmentSatisfaction : [2 3 4 1]
JobInvolvement          : [3 2 4 1]
JobLevel                : [2 1 3 4 5]
JobSatisfaction         : [4 2 3 1]
PerformanceRating       : [3 4]
RelationshipSatisfaction: [1 4 2 3]
Shift                   : [0 1 3 2]
WorkLifeBalance         : [1 3 2 4]

#### Ordinal mapping for numerical values

In [75]:
from sklearn.preprocessing import MinMaxScaler

In [76]:
scale_5 = MinMaxScaler(feature_range=(1, 5))
scale_4 = MinMaxScaler(feature_range=(1, 4))

In [77]:
data['Education'] = scale_5.fit_transform(data[['Education']])
data['JobLevel'] = scale_5.fit_transform(data[['JobLevel']])

In [78]:
data.sample(7)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
393,34,1381,4,4.0,3,72,3,2.0,3,6538,...,3,1,1,6,3,3,3,2,1,2
100,37,807,6,4.0,3,63,3,1.0,1,2073,...,4,4,0,7,3,3,3,2,0,2
270,55,452,1,3.0,4,81,3,5.0,1,19045,...,3,3,0,37,2,3,36,10,4,13
555,35,1225,2,4.0,4,61,3,2.0,1,5093,...,3,1,1,16,2,4,1,0,0,0
164,27,1450,3,3.0,3,79,2,1.0,3,2566,...,3,4,1,1,2,2,1,1,0,1
1510,31,655,7,4.0,4,48,3,2.0,4,5915,...,4,4,1,10,3,2,7,7,1,7
548,23,650,9,1.0,2,37,3,1.0,1,2500,...,3,4,1,5,2,4,4,3,0,2

In [79]:
print(data['Education'].unique())
print(data['JobLevel'].unique())

[2. 1. 4. 3. 5.]
[2. 1. 3. 4. 5.]

In [80]:
data['EnvironmentSatisfaction'] = scale_4.fit_transform(data[['EnvironmentSatisfaction']])
data['JobInvolvement'] = scale_4.fit_transform(data[['JobInvolvement']])
data['JobSatisfaction'] = scale_4.fit_transform(data[['JobSatisfaction']])
data['RelationshipSatisfaction'] = scale_4.fit_transform(data[['RelationshipSatisfaction']])
data['Shift'] = scale_4.fit_transform(data[['Shift']])
data['WorkLifeBalance'] = scale_4.fit_transform(data[['WorkLifeBalance']])

In [81]:
data.sample(15)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
776,51,1323,4,4.0,1.0,34,3.0,1.0,3.0,2461,...,3,3.0,4.0,18,2,4.0,10,0,2,7
760,34,1333,10,4.0,3.0,87,3.0,1.0,3.0,2220,...,3,4.0,2.0,1,2,3.0,1,1,0,0
1121,39,1462,6,3.0,4.0,38,4.0,3.0,3.0,8237,...,3,1.0,2.0,11,3,3.0,7,6,7,6
843,35,819,2,3.0,3.0,44,2.0,3.0,2.0,10274,...,3,2.0,2.0,15,2,4.0,7,7,6,4
933,45,364,25,3.0,2.0,83,3.0,5.0,2.0,18061,...,4,3.0,1.0,22,4,3.0,0,0,0,0
1603,45,930,9,3.0,4.0,74,3.0,3.0,1.0,10761,...,3,3.0,2.0,18,2,3.0,5,4,0,2
1565,37,342,16,4.0,4.0,66,2.0,2.0,3.0,6334,...,3,4.0,3.0,9,2,3.0,1,0,0,0
1115,26,474,3,3.0,1.0,89,3.0,1.0,4.0,2061,...,4,1.0,1.0,1,5,3.0,1,0,0,0
1466,37,1115,1,4.0,1.0,51,2.0,2.0,3.0,5993,...,3,3.0,2.0,7,2,4.0,7,5,0,7
653,33,1075,3,2.0,4.0,57,3.0,1.0,2.0,2277,...,3,3.0,2.0,7,4,4.0,4,3,0,3
482,35,538,25,2.0,1.0,54,2.0,2.0,4.0,3681,...,3,4.0,1.0,9,3,3.0,3,2,0,2
1533,33,1141,1,3.0,3.0,42,4.0,2.0,1.0,5376,...,3,1.0,3.0,10,3,3.0,5,3,1,3
284,26,496,11,2.0,1.0,60,3.0,2.0,1.0,4741,...,3,3.0,2.0,5,3,3.0,5,3,3,3
1360,28,783,1,2.0,3.0,42,2.0,2.0,4.0,6834,...,3,3.0,2.0,7,2,3.0,7,7,0,7
1199,38,1495,4,2.0,4.0,87,3.0,1.0,3.0,3306,...,3,4.0,2.0,7,5,2.0,0,0,0,0

In [82]:
data['PerformanceRating'] = data['PerformanceRating'].map({1: 1.0, 2: 2.0, 3: 3.0, 4: 4.0})
data.sample(10)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
623,45,930,9,3.0,4.0,74,3.0,3.0,1.0,10761,...,3.0,3.0,2.0,18,2,3.0,5,4,0,2
1355,34,735,3,1.0,4.0,75,2.0,2.0,4.0,8103,...,3.0,3.0,1.0,9,3,2.0,4,2,0,1
383,22,253,11,3.0,1.0,43,3.0,1.0,2.0,2244,...,3.0,4.0,2.0,2,1,3.0,2,1,1,2
313,33,553,5,4.0,4.0,74,3.0,3.0,2.0,11878,...,3.0,2.0,3.0,12,2,3.0,10,6,8,8
140,32,1033,9,3.0,1.0,41,3.0,1.0,1.0,4200,...,4.0,1.0,1.0,10,2,4.0,5,4,0,4
1454,35,287,1,4.0,3.0,62,1.0,1.0,4.0,2977,...,3.0,4.0,2.0,4,5,3.0,4,3,1,1
556,32,430,24,4.0,1.0,80,3.0,2.0,4.0,5309,...,3.0,4.0,3.0,10,2,3.0,10,8,4,7
1473,38,1189,1,3.0,4.0,90,3.0,2.0,4.0,4735,...,3.0,4.0,3.0,19,4,4.0,13,11,2,9
1383,29,136,1,3.0,1.0,89,3.0,2.0,1.0,5373,...,3.0,1.0,2.0,6,5,2.0,5,3,0,2
495,44,1315,3,4.0,4.0,35,3.0,5.0,4.0,19513,...,3.0,1.0,2.0,26,2,4.0,2,2,0,1

In [83]:
data['PerformanceRating'].unique()

array([3., 4.])

In [84]:
for col in data.columns:
    if (data[col].nunique() >= 7):
        print(f'{col:<{max_len}}: {data[col].nunique()}')

Age                     : 43
DailyRate               : 886
DistanceFromHome        : 29
HourlyRate              : 71
MonthlyIncome           : 1349
MonthlyRate             : 1427
NumCompaniesWorked      : 10
PercentSalaryHike       : 15
TotalWorkingYears       : 40
TrainingTimesLastYear   : 7
YearsAtCompany          : 37
YearsInCurrentRole      : 19
YearsSinceLastPromotion : 16
YearsWithCurrManager    : 18

In [85]:
data['PercentSalaryHike'].unique()

array([11, 23, 15, 12, 13, 20, 22, 21, 17, 14, 16, 18, 19, 24, 25])

In [86]:
data.head(7)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2.0,2.0,94,3.0,2.0,4.0,5993,...,3.0,1.0,1.0,8,0,1.0,6,4,0,5
1,49,279,8,1.0,3.0,61,2.0,2.0,2.0,5130,...,4.0,4.0,2.0,10,3,3.0,10,7,1,7
2,37,1373,2,2.0,4.0,92,2.0,1.0,3.0,2090,...,3.0,2.0,1.0,7,3,3.0,0,0,0,0
3,33,1392,3,4.0,4.0,56,3.0,1.0,3.0,2909,...,3.0,3.0,1.0,8,3,3.0,8,7,3,0
4,27,591,2,1.0,1.0,40,3.0,1.0,2.0,3468,...,3.0,4.0,2.0,6,3,3.0,2,2,2,2
5,32,1005,2,2.0,4.0,79,3.0,1.0,4.0,3068,...,3.0,3.0,1.0,8,2,2.0,7,7,3,6
6,59,1324,3,3.0,3.0,81,4.0,1.0,1.0,2670,...,4.0,1.0,4.0,12,3,2.0,1,0,0,0

In [87]:
Object_df.head(7)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole
0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.0,2.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
2,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,2.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.0,1.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5,0.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
6,0.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0