In [89]:
import pandas as pd

In [90]:
data = pd.read_csv('watson_healthcare_modified.csv')
data.sample(4)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
88,1535342,30,No,Travel_Rarely,288,Maternity,2,3,Life Sciences,1,...,1,80,3,11,3,3,11,10,10,8
399,1413436,31,No,Travel_Rarely,329,Maternity,1,2,Life Sciences,1,...,3,80,1,4,3,3,4,2,3,2
336,1701544,29,Yes,Travel_Rarely,318,Maternity,8,4,Other,1,...,4,80,0,7,4,2,7,7,0,7
658,1870106,58,Yes,Travel_Frequently,781,Maternity,2,1,Life Sciences,1,...,4,80,1,3,3,2,1,0,0,0

In [91]:
data.shape

(1676, 35)

In [92]:
data.select_dtypes(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,No,Travel_Rarely,Cardiology,Life Sciences,Female,Nurse,Single,Y,Yes
1,No,Travel_Frequently,Maternity,Life Sciences,Male,Other,Married,Y,No
2,Yes,Travel_Rarely,Maternity,Other,Male,Nurse,Single,Y,Yes
3,No,Travel_Frequently,Maternity,Life Sciences,Female,Other,Married,Y,Yes
4,No,Travel_Rarely,Maternity,Medical,Male,Nurse,Married,Y,No
...,...,...,...,...,...,...,...,...,...
1671,Yes,Travel_Rarely,Neurology,Technical Degree,Male,Nurse,Single,Y,Yes
1672,No,Travel_Rarely,Cardiology,Marketing,Female,Nurse,Married,Y,Yes
1673,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
1674,No,Travel_Rarely,Neurology,Life Sciences,Female,Therapist,Married,Y,No
1675,No,Travel_Rarely,Cardiology,Medical,Female,Nurse,Single,Y,No

In [93]:
df = data.copy()
df.tail(5)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1671,1117656,26,Yes,Travel_Rarely,471,Neurology,24,3,Technical Degree,1,...,2,80,0,1,3,1,1,0,0,0
1672,1152327,46,No,Travel_Rarely,1125,Cardiology,10,3,Marketing,1,...,3,80,1,15,3,3,3,2,1,2
1673,1812428,20,No,Travel_Rarely,959,Maternity,1,3,Life Sciences,1,...,4,80,0,1,0,4,1,0,0,0
1674,1812429,39,No,Travel_Rarely,466,Neurology,1,1,Life Sciences,1,...,3,80,1,21,3,3,21,6,11,8
1675,1152329,27,No,Travel_Rarely,511,Cardiology,2,2,Medical,1,...,2,80,0,9,5,2,8,7,0,7

In [94]:
del data # For original dataset safety

In [95]:
df = df.select_dtypes(include='object')
display(df.shape)
df.sample(4)

(1676, 9)

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
1146,No,Travel_Rarely,Maternity,Other,Male,Nurse,Divorced,Y,No
769,No,Travel_Frequently,Maternity,Medical,Female,Other,Married,Y,No
23,No,Travel_Rarely,Maternity,Life Sciences,Male,Other,Single,Y,No
391,No,Travel_Rarely,Maternity,Medical,Female,Nurse,Married,Y,No

In [96]:
df.drop(columns=['Over18'], inplace=True)
df.sample(6)
display(df.shape)

(1676, 8)

In [97]:
from sklearn.preprocessing import OneHotEncoder

In [98]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='error', dtype='int64').set_output(transform='pandas')

### Encoding Objects to Numerical Values

#### Gender encoding (ohe) and merging

In [99]:
enc_gender = ohe.fit_transform(df[['Gender']])

In [100]:
enc_gender.sample(5)

      Gender_Female  Gender_Male
194               0            1
1024              1            0
570               1            0
1400              0            1
1504              1            0

In [101]:
df = pd.concat([df, enc_gender], axis=1).drop(columns=['Gender'])
display(df.shape)
df.sample(7)

(1676, 9)

,Attrition,BusinessTravel,Department,EducationField,JobRole,MaritalStatus,OverTime,Gender_Female,Gender_Male
918,Yes,Travel_Frequently,Maternity,Medical,Nurse,Single,Yes,0,1
221,No,Travel_Rarely,Maternity,Medical,Other,Married,No,1,0
807,No,Travel_Rarely,Cardiology,Marketing,Administrative,Married,No,0,1
638,No,Non-Travel,Maternity,Life Sciences,Nurse,Married,No,0,1
585,No,Travel_Rarely,Maternity,Life Sciences,Nurse,Married,No,1,0
1238,No,Travel_Rarely,Cardiology,Life Sciences,Nurse,Married,No,0,1
866,No,Travel_Rarely,Maternity,Life Sciences,Administrative,Married,No,0,1

#### OverTime and Attrition encoding (mapping to 1s and 0s)

In [102]:
# yes = 1 | no = 0 
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})  
df['OverTime'] = df['OverTime'].map({'Yes': 1, 'No': 0})

In [105]:
df.head(3)

,Attrition,BusinessTravel,Department,EducationField,JobRole,MaritalStatus,OverTime,Gender_Female,Gender_Male
0,0,Travel_Rarely,Cardiology,Life Sciences,Nurse,Single,1,1,0
1,0,Travel_Frequently,Maternity,Life Sciences,Other,Married,0,0,1
2,1,Travel_Rarely,Maternity,Other,Nurse,Single,1,0,1

In [109]:
print(f'Attrition      = {df.Attrition.unique()}')
print(f'OverTime       = {df.OverTime.unique()}')
print(f'Gender         = {df.Gender_Male.unique()}')
print(f'Gender         = {df.Gender_Female.unique()}')
print(f'BusinessTravel = {df.BusinessTravel.unique()}')
print(f'Department     = {df.Department.unique()}')
print(f'JobRole        = {df.JobRole.unique()}')

Attrition      = [0 1]
OverTime       = [1 0]
Gender         = [0 1]
Gender         = [1 0]
BusinessTravel = ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
Department     = ['Cardiology' 'Maternity' 'Neurology']
JobRole        = ['Nurse' 'Other' 'Therapist' 'Administrative' 'Admin']