In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Feature_extracted_dataset(whd).csv')
df

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
0,1313919,41,8,5993,Yes,1,6,19479,3,Nurse,2,4,0,5,2,0,1,11,Single,No
1,1200302,49,10,5130,No,8,10,24907,2,Other,2,7,1,7,3,1,3,23,Married,No
2,1060315,37,7,2090,Yes,2,0,2396,2,Nurse,1,0,0,0,4,0,3,15,Single,Yes
3,1272912,33,8,2909,Yes,3,8,23159,3,Other,1,7,3,0,4,0,3,11,Married,No
4,1414939,27,6,3468,No,2,2,16632,3,Nurse,1,2,2,2,1,1,3,12,Married,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,1117656,26,1,2340,Yes,24,1,23213,1,Nurse,1,0,0,0,3,0,1,18,Single,Yes
1672,1152327,46,15,9071,Yes,10,3,11563,2,Nurse,3,2,1,2,3,1,3,19,Married,No
1673,1812428,20,1,2836,No,1,1,11757,2,Other,1,0,0,0,4,0,4,13,Single,No
1674,1812429,39,21,12742,No,1,21,7060,2,Therapist,4,6,11,8,4,1,3,16,Married,No
1675,1152329,27,9,6500,No,2,8,26997,4,Nurse,2,7,0,7,1,0,2,14,Single,No

In [4]:
df.isnull().any()

EmployeeID                 False
Age                        False
TotalWorkingYears          False
MonthlyIncome              False
OverTime                   False
DistanceFromHome           False
YearsAtCompany             False
MonthlyRate                False
JobInvolvement             False
JobRole                    False
JobLevel                   False
YearsInCurrentRole         False
YearsSinceLastPromotion    False
YearsWithCurrManager       False
EnvironmentSatisfaction    False
Shift                      False
WorkLifeBalance            False
PercentSalaryHike          False
MaritalStatus              False
Attrition                  False
dtype: bool

In [5]:
df.duplicated().any()

np.False_

In [6]:
df['OverTime'] = df['OverTime'].map({'Yes': 1, 'No': 0})

In [7]:
df['OverTime'].sample(5)

1158    1
530     0
1530    0
553     0
1652    1
Name: OverTime, dtype: int64

In [8]:
df.columns

Index(['EmployeeID', 'Age', 'TotalWorkingYears', 'MonthlyIncome', 'OverTime',
       'DistanceFromHome', 'YearsAtCompany', 'MonthlyRate', 'JobInvolvement',
       'JobRole', 'JobLevel', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'EnvironmentSatisfaction', 'Shift',
       'WorkLifeBalance', 'PercentSalaryHike', 'MaritalStatus', 'Attrition'],
      dtype='object')

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['MonthlyIncome'] = scaler.fit_transform(df[['MonthlyIncome']])
df['TotalWorkingYears'] = scaler.fit_transform(df[['TotalWorkingYears']])
df['DistanceFromHome'] = scaler.fit_transform(df[['DistanceFromHome']])
df['YearsAtCompany'] = scaler.fit_transform(df[['YearsAtCompany']])
df['MonthlyRate'] = scaler.fit_transform(df[['MonthlyRate']])
df['JobInvolvement'] = scaler.fit_transform(df[['JobInvolvement']])
df['JobLevel'] = scaler.fit_transform(df[['JobLevel']])
df['YearsInCurrentRole'] = scaler.fit_transform(df[['YearsInCurrentRole']])
df['EnvironmentSatisfaction'] = scaler.fit_transform(df[['EnvironmentSatisfaction']])
df['Shift'] = scaler.fit_transform(df[['Shift']])
df['WorkLifeBalance'] = scaler.fit_transform(df[['WorkLifeBalance']])
df['PercentSalaryHike'] = scaler.fit_transform(df[['PercentSalaryHike']])

In [10]:
df.head(5)

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
0,1313919,41,0.200,0.262454,1,0.000000,0.15,0.698053,0.666667,Nurse,0.25,0.222222,0,5,0.333333,0.000000,0.000000,0.000000,Single,No
1,1200302,49,0.250,0.217009,0,0.250000,0.25,0.916001,0.333333,Other,0.25,0.388889,1,7,0.666667,0.333333,0.666667,0.857143,Married,No
2,1060315,37,0.175,0.056925,1,0.035714,0.00,0.012126,0.333333,Nurse,0.00,0.000000,0,0,1.000000,0.000000,0.666667,0.285714,Single,Yes
3,1272912,33,0.200,0.100053,1,0.071429,0.20,0.845814,0.666667,Other,0.00,0.388889,3,0,1.000000,0.000000,0.666667,0.000000,Married,No
4,1414939,27,0.150,0.129489,0,0.035714,0.05,0.583738,0.666667,Nurse,0.00,0.111111,2,2,0.000000,0.333333,0.666667,0.071429,Married,No

In [11]:
df['MaritalStatus'] = df['MaritalStatus'].map({'Single': 0, 'Married': 1, 'Divorced': 2})
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})

In [12]:
df.sample(5)

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
1605,1637476,34,0.050,0.091259,0,0.285714,0.050,0.039269,0.666667,Other,0.00,0.111111,2,2,0.000000,0.000000,0.666667,0.285714,1,0
670,1206644,42,0.250,0.275671,0,0.464286,0.125,0.230074,0.333333,Nurse,0.25,0.222222,0,3,0.666667,0.000000,0.666667,0.428571,0,0
749,1330619,36,0.450,0.091311,0,0.535714,0.425,0.247942,1.000000,Nurse,0.00,0.722222,15,14,0.666667,0.000000,0.666667,0.357143,0,0
658,1870106,58,0.075,0.072196,1,0.035714,0.025,0.453323,0.333333,Nurse,0.00,0.000000,0,0,1.000000,0.333333,0.333333,0.214286,2,1
479,1209208,30,0.025,0.053923,0,0.392857,0.025,0.496928,0.333333,Other,0.00,0.000000,0,0,0.333333,0.333333,1.000000,0.500000,1,1

In [13]:
df['JobRole'].unique()

array(['Nurse', 'Other', 'Therapist', 'Administrative', 'Admin'],
      dtype=object)

In [14]:
df['JobRole'] = df['JobRole'].map({'Nurse': 1, 'Therapist': 2, 'Administrative': 3, 'Admin': 4, 'Other': 0})
df.sample(7)

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
520,1510616,37,0.100,0.193312,0,0.321429,0.025,0.527525,1.000000,0,0.00,0.000000,0,0,1.000000,0.000000,0.666667,0.428571,0,0
184,1477195,53,0.125,0.181201,0,0.428571,0.100,0.969926,1.000000,2,0.25,0.111111,1,3,1.000000,0.666667,0.666667,0.000000,2,0
1025,1743607,41,0.175,0.058873,1,0.142857,0.100,0.139209,1.000000,0,0.00,0.111111,0,3,0.333333,0.000000,0.333333,0.071429,1,0
874,1126413,46,0.300,0.335440,0,0.035714,0.150,0.615900,0.666667,2,0.25,0.166667,1,4,1.000000,0.333333,0.333333,0.000000,2,0
936,1111156,32,0.250,0.204002,0,0.214286,0.250,0.833206,0.666667,1,0.25,0.222222,1,1,1.000000,0.333333,0.666667,0.500000,1,0
1071,1285005,33,0.350,0.283254,1,0.250000,0.000,0.801245,0.666667,1,0.25,0.000000,0,0,1.000000,0.000000,0.666667,0.428571,0,0
483,1761086,31,0.325,0.234387,0,0.178571,0.175,0.165629,1.000000,1,0.25,0.388889,5,7,0.000000,0.666667,1.000000,0.785714,2,0

In [15]:
# df.to_csv('Partially_cleaned_dataset.csv', index=False)

In [20]:
attrition_0 = (df['Attrition'] == 0).sum()
attrition_1 = (df['Attrition'] == 1).sum()

print('Attrition_Yes: ', attrition_1,'\n')
print('Attrition_No:  ', attrition_0)

Attrition_Yes:  199

Attrition_No:   1477