In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv('watson_healthcare_modified.csv')
dataframe.sample(4)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
346,1477474,41,No,Travel_Rarely,483,Neurology,6,3,Medical,1,...,4,80,0,8,3,3,5,4,1,2
1574,1220579,39,No,Travel_Rarely,360,Maternity,23,3,Medical,1,...,1,80,0,6,2,3,5,2,0,3
1247,1176037,29,No,Travel_Frequently,461,Maternity,1,3,Life Sciences,1,...,4,80,0,10,5,4,3,2,0,2
554,1446990,53,No,Travel_Rarely,346,Maternity,6,3,Life Sciences,1,...,4,80,0,19,4,3,2,2,2,2

In [3]:
dataframe.shape

(1676, 35)

In [4]:
dataframe.select_dtypes(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,No,Travel_Rarely,Cardiology,Life Sciences,Female,Nurse,Single,Y,Yes
1,No,Travel_Frequently,Maternity,Life Sciences,Male,Other,Married,Y,No
2,Yes,Travel_Rarely,Maternity,Other,Male,Nurse,Single,Y,Yes
3,No,Travel_Frequently,Maternity,Life Sciences,Female,Other,Married,Y,Yes
4,No,Travel_Rarely,Maternity,Medical,Male,Nurse,Married,Y,No
...,...,...,...,...,...,...,...,...,...
1671,Yes,Travel_Rarely,Neurology,Technical Degree,Male,Nurse,Single,Y,Yes
1672,No,Travel_Rarely,Cardiology,Marketing,Female,Nurse,Married,Y,Yes
1673,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
1674,No,Travel_Rarely,Neurology,Life Sciences,Female,Therapist,Married,Y,No
1675,No,Travel_Rarely,Cardiology,Medical,Female,Nurse,Single,Y,No

In [5]:
dframe = dataframe.copy()
dframe.tail(5)
del dataframe # For original dataset safety

In [6]:
data = dframe.select_dtypes(include='int64')
data.columns

Index(['EmployeeID', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'Shift', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [7]:
df = dframe.select_dtypes(include='object')
display(df.shape)
df.sample(4)

(1676, 9)

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
235,No,Travel_Rarely,Cardiology,Marketing,Female,Administrative,Married,Y,Yes
616,No,Travel_Rarely,Maternity,Medical,Male,Other,Single,Y,No
38,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Married,Y,Yes
1279,No,Travel_Rarely,Maternity,Life Sciences,Male,Other,Married,Y,No

In [8]:
(dframe.dtypes).unique()

array([dtype('int64'), dtype('O')], dtype=object)

In [9]:
del dframe # Save memory

#### Dropping Over18 and EducationField

In [10]:
df.drop(columns=['Over18'], inplace=True)
df.sample(6)
display(df.shape)

(1676, 8)

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='error').set_output(transform='pandas')

### Encoding Objects to Numerical Values

#### Gender and Department encoding (ohe) and merging

In [14]:
enc_gender = ohe.fit_transform(df[['Gender']])
enc_department = ohe.fit_transform(df[['Department']])

In [15]:
enc_gender.sample(5)

      Gender_Female  Gender_Male
406             0.0          1.0
1534            1.0          0.0
327             1.0          0.0
719             0.0          1.0
1667            0.0          1.0

In [16]:
enc_department.sample(4)

      Department_Cardiology  Department_Maternity  Department_Neurology
92                      1.0                   0.0                   0.0
517                     0.0                   1.0                   0.0
339                     1.0                   0.0                   0.0
1191                    1.0                   0.0                   0.0

In [17]:
df = pd.concat([df, enc_department], axis=1).drop(columns=['Department'])
display(df.shape)
df.sample(5)

(1676, 10)

,Attrition,BusinessTravel,EducationField,Gender,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology
1546,No,Travel_Rarely,Life Sciences,Male,Nurse,Divorced,No,0.0,1.0,0.0
1645,No,Travel_Rarely,Life Sciences,Male,Nurse,Married,No,1.0,0.0,0.0
1134,Yes,Non-Travel,Other,Female,Other,Married,Yes,0.0,1.0,0.0
642,No,Travel_Rarely,Life Sciences,Male,Other,Married,Yes,0.0,1.0,0.0
1630,No,Travel_Frequently,Medical,Male,Other,Married,No,1.0,0.0,0.0

In [18]:
df = pd.concat([df, enc_gender], axis=1).drop(columns=['Gender'])
display(df.shape)
df.sample(7)

(1676, 11)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
691,No,Travel_Rarely,Life Sciences,Nurse,Married,Yes,1.0,0.0,0.0,0.0,1.0
480,No,Travel_Rarely,Life Sciences,Other,Married,Yes,0.0,1.0,0.0,0.0,1.0
1205,No,Travel_Rarely,Medical,Nurse,Married,No,0.0,1.0,0.0,0.0,1.0
408,No,Travel_Rarely,Life Sciences,Other,Married,No,0.0,0.0,1.0,1.0,0.0
1424,No,Travel_Rarely,Medical,Other,Married,No,1.0,0.0,0.0,0.0,1.0
401,No,Travel_Frequently,Life Sciences,Nurse,Married,No,1.0,0.0,0.0,1.0,0.0
548,No,Travel_Rarely,Medical,Nurse,Married,No,0.0,1.0,0.0,0.0,1.0

#### OverTime and Attrition encoding (mapping to 1s and 0s)

In [19]:
# yes = 1 | no = 0 
df['Attrition'] = df['Attrition'].map({'Yes': 1.0, 'No': 0.0})  
df['OverTime'] = df['OverTime'].map({'Yes': 1.0, 'No': 0.0})

In [20]:
df.head(3)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
0,0.0,Travel_Rarely,Life Sciences,Nurse,Single,1.0,1.0,0.0,0.0,1.0,0.0
1,0.0,Travel_Frequently,Life Sciences,Other,Married,0.0,0.0,1.0,0.0,0.0,1.0
2,1.0,Travel_Rarely,Other,Nurse,Single,1.0,0.0,1.0,0.0,0.0,1.0

#### Ordinal encoding for BusinessTravel and MaritalStatus

In [22]:
travel_frequency = ['Non-Travel', 'Travel_Rarely', 'Travel_Frequently'] # 0.0 = Non-Travel, 1.0 = Travel_Rarely, 2.0 = Travel_Frequently
marital_status = ['Single','Married', 'Divorced']

In [23]:
from sklearn.preprocessing import OrdinalEncoder

In [24]:
oe_travel = OrdinalEncoder(categories=[travel_frequency])
oe_marital_status = OrdinalEncoder(categories= [marital_status])

In [25]:
df['BusinessTravel'] = oe_travel.fit_transform(df[['BusinessTravel']])

In [26]:
df['MaritalStatus'] = oe_marital_status.fit_transform(df[['MaritalStatus']])

In [28]:
df.sample(10)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1304,0.0,1.0,Medical,Other,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1229,0.0,1.0,Life Sciences,Therapist,1.0,0.0,0.0,1.0,0.0,0.0,1.0
436,0.0,1.0,Marketing,Other,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1142,0.0,1.0,Life Sciences,Therapist,1.0,1.0,0.0,1.0,0.0,1.0,0.0
462,1.0,1.0,Technical Degree,Nurse,0.0,1.0,0.0,1.0,0.0,0.0,1.0
270,0.0,1.0,Medical,Other,0.0,1.0,0.0,0.0,1.0,0.0,1.0
579,0.0,1.0,Life Sciences,Nurse,1.0,0.0,0.0,1.0,0.0,0.0,1.0
316,0.0,1.0,Technical Degree,Nurse,0.0,1.0,0.0,1.0,0.0,1.0,0.0
746,0.0,1.0,Marketing,Administrative,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1454,0.0,1.0,Life Sciences,Other,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [29]:
max_len = max(len(col) for col in df.columns) # finds the length of the largest column name

for col in df.columns:
    print(f'{col:<{max_len}} = {df[col].unique()}') # left aligns the column name

del max_len

Attrition             = [0. 1.]
BusinessTravel        = [1. 2. 0.]
EducationField        = ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
JobRole               = ['Nurse' 'Other' 'Therapist' 'Administrative' 'Admin']
MaritalStatus         = [0. 1. 2.]
OverTime              = [1. 0.]
Department_Cardiology = [1. 0.]
Department_Maternity  = [0. 1.]
Department_Neurology  = [0. 1.]
Gender_Female         = [1. 0.]
Gender_Male           = [0. 1.]

In [30]:
df[df['JobRole'] == 'Other'].count()

Attrition                534
BusinessTravel           534
EducationField           534
JobRole                  534
MaritalStatus            534
OverTime                 534
Department_Cardiology    534
Department_Maternity     534
Department_Neurology     534
Gender_Female            534
Gender_Male              534
dtype: int64

In [31]:
df[df['EducationField'] == 'Other'].count()

Attrition                88
BusinessTravel           88
EducationField           88
JobRole                  88
MaritalStatus            88
OverTime                 88
Department_Cardiology    88
Department_Maternity     88
Department_Neurology     88
Gender_Female            88
Gender_Male              88
dtype: int64

In [32]:
df.sample(7)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
611,0.0,1.0,Human Resources,Other,1.0,0.0,0.0,0.0,1.0,0.0,1.0
1241,0.0,2.0,Technical Degree,Other,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1305,0.0,1.0,Marketing,Other,1.0,1.0,1.0,0.0,0.0,1.0,0.0
47,0.0,1.0,Life Sciences,Other,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1244,0.0,1.0,Technical Degree,Nurse,1.0,0.0,1.0,0.0,0.0,0.0,1.0
784,0.0,2.0,Life Sciences,Therapist,1.0,0.0,0.0,0.0,1.0,0.0,1.0
1436,0.0,2.0,Life Sciences,Therapist,2.0,0.0,1.0,0.0,0.0,1.0,0.0

#### JobRole and EducationField encoding (categorical mapping)

In [33]:
df['EducationField'] = df['EducationField'].map({'Other': 0.0, 'Life Sciences': 1.0, 'Medical': 2.0, 'Marketing': 3.0, 'Technical Degree': 4.0, 'Human Resources': 5.0})
df['is_other_JobRole'] = (df['JobRole'] == 'Other')
df['JobRole'] = df['JobRole'].map({'Other': 0.0, 'Nurse': 1.0,'Therapist': 2.0, 'Administrative': 3.0, 'Admin': 4.0})

In [35]:
display(df.shape)
df.sample(10)

(1676, 12)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole
373,0.0,1.0,2.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,False
1508,0.0,2.0,2.0,4.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,False
1066,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,True
459,0.0,1.0,2.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,False
1219,1.0,1.0,5.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,True
1649,0.0,1.0,4.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,True
204,1.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,False
714,0.0,2.0,2.0,3.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,False
1279,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,True
1408,0.0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,False

In [36]:
df.isna().any()

Attrition                False
BusinessTravel           False
EducationField           False
JobRole                  False
MaritalStatus            False
OverTime                 False
Department_Cardiology    False
Department_Maternity     False
Department_Neurology     False
Gender_Female            False
Gender_Male              False
is_other_JobRole         False
dtype: bool

In [37]:
Object_df = df
del df # For Object data safety

### Scaling Numberical Values

In [38]:
print(f'Number of Columns: {len(data.columns)}')
data.columns

Number of Columns: 26

Index(['EmployeeID', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'Shift', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [39]:
max_len = max(len(col) for col in data.columns) 
for col in data.columns:
    print(f'{col:<{max_len}}: {data[col].nunique()}')

EmployeeID              : 1676
Age                     : 43
DailyRate               : 886
DistanceFromHome        : 29
Education               : 5
EmployeeCount           : 1
EnvironmentSatisfaction : 4
HourlyRate              : 71
JobInvolvement          : 4
JobLevel                : 5
JobSatisfaction         : 4
MonthlyIncome           : 1349
MonthlyRate             : 1427
NumCompaniesWorked      : 10
PercentSalaryHike       : 15
PerformanceRating       : 2
RelationshipSatisfaction: 4
StandardHours           : 1
Shift                   : 4
TotalWorkingYears       : 40
TrainingTimesLastYear   : 7
WorkLifeBalance         : 4
YearsAtCompany          : 37
YearsInCurrentRole      : 19
YearsSinceLastPromotion : 16
YearsWithCurrManager    : 18

In [40]:
data.columns[data.nunique() == 1]

Index(['EmployeeCount', 'StandardHours'], dtype='object')

In [41]:
print(data['EmployeeCount'].unique())
print(data['StandardHours'].unique())

[1]
[80]

In [42]:
data.shape

(1676, 26)

In [43]:
# dropping EmployeeCount and StandardHours due to lack of variety 
data.drop(['EmployeeCount', 'StandardHours'], axis=1, inplace=True)

In [44]:
data.shape

(1676, 24)

In [45]:
data.sample(4)

,EmployeeID,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
366,1866571,41,143,4,3,1,56,3,2,2,...,3,3,0,8,5,3,8,7,7,7
1337,1494882,36,1266,10,4,2,63,2,2,3,...,3,1,1,10,4,3,10,9,1,7
1244,1692811,31,1003,5,3,1,51,3,2,3,...,3,3,1,6,3,3,5,2,0,2
703,1785279,39,903,2,5,1,41,4,3,3,...,3,4,0,9,3,3,8,7,0,7

#### Dropping EmployeeID column

In [46]:
data.drop('EmployeeID', axis=1, inplace=True)
data.sample(4)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
353,37,1319,6,3,3,51,4,2,1,5974,...,3,1,2,13,2,3,7,7,6,7
139,30,1240,9,3,3,48,3,2,4,6347,...,3,4,0,12,2,1,11,9,4,7
643,29,341,1,3,2,48,2,1,3,2800,...,3,3,3,5,3,3,3,2,0,2
1181,54,584,22,5,2,91,3,4,3,17426,...,4,3,1,36,6,3,10,8,4,7

In [48]:
for col in data.columns:
    if (data[col].nunique() < 7):
        print(f'{col:<{max_len}}: {data[col].unique()}')

Education               : [2 1 4 3 5]
EnvironmentSatisfaction : [2 3 4 1]
JobInvolvement          : [3 2 4 1]
JobLevel                : [2 1 3 4 5]
JobSatisfaction         : [4 2 3 1]
PerformanceRating       : [3 4]
RelationshipSatisfaction: [1 4 2 3]
Shift                   : [0 1 3 2]
WorkLifeBalance         : [1 3 2 4]

#### Ordinal mapping for numerical values

In [49]:
from sklearn.preprocessing import MinMaxScaler

In [50]:
scale_5 = MinMaxScaler(feature_range=(1, 5))
scale_4 = MinMaxScaler(feature_range=(1, 4))

In [51]:
data['Education'] = scale_5.fit_transform(data[['Education']])
data['JobLevel'] = scale_5.fit_transform(data[['JobLevel']])

In [53]:
data.sample(7)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1090,42,288,2,3.0,4,40,3,3.0,4,10124,...,3,3,1,24,3,1,20,8,13,9
186,40,989,4,1.0,4,46,3,5.0,3,19033,...,3,2,1,21,2,3,20,8,9,9
979,38,693,7,3.0,4,57,4,1.0,3,2610,...,3,4,3,4,2,3,4,2,0,3
699,53,1376,2,2.0,3,45,3,4.0,3,14852,...,3,3,1,22,3,4,17,13,15,2
1611,36,311,7,3.0,1,77,3,1.0,2,2013,...,3,3,0,15,4,3,4,3,1,3
1338,31,311,20,3.0,2,89,3,2.0,3,4197,...,3,1,1,10,2,3,10,8,0,2
26,32,1125,16,1.0,2,72,1,1.0,1,3919,...,4,2,0,10,5,3,10,2,6,7

In [54]:
print(data['Education'].unique())
print(data['JobLevel'].unique())

[2. 1. 4. 3. 5.]
[2. 1. 3. 4. 5.]

In [55]:
data['EnvironmentSatisfaction'] = scale_4.fit_transform(data[['EnvironmentSatisfaction']])
data['JobInvolvement'] = scale_4.fit_transform(data[['JobInvolvement']])
data['JobSatisfaction'] = scale_4.fit_transform(data[['JobSatisfaction']])
data['RelationshipSatisfaction'] = scale_4.fit_transform(data[['RelationshipSatisfaction']])
data['Shift'] = scale_4.fit_transform(data[['Shift']])
data['WorkLifeBalance'] = scale_4.fit_transform(data[['WorkLifeBalance']])

In [56]:
data.sample(15)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
516,38,243,7,4.0,4.0,46,2.0,2.0,4.0,4028,...,4,1.0,1.0,8,2,3.0,7,7,0,5
794,26,1330,21,3.0,1.0,37,3.0,1.0,3.0,2377,...,4,3.0,2.0,1,0,2.0,1,1,0,0
1640,35,144,22,3.0,4.0,46,1.0,1.0,3.0,4230,...,3,3.0,1.0,6,2,3.0,5,4,4,3
1248,30,979,15,2.0,3.0,94,2.0,3.0,1.0,7140,...,3,1.0,2.0,12,2,3.0,7,7,1,7
1297,34,810,8,2.0,2.0,92,4.0,2.0,3.0,6799,...,4,3.0,3.0,10,5,3.0,10,8,4,8
980,34,404,2,4.0,3.0,98,3.0,2.0,4.0,6687,...,3,4.0,1.0,14,2,4.0,14,11,4,11
1104,38,888,10,4.0,3.0,71,3.0,2.0,3.0,6077,...,3,3.0,1.0,10,2,3.0,6,3,1,2
797,28,1009,1,3.0,1.0,45,2.0,1.0,2.0,2596,...,3,1.0,3.0,1,2,3.0,1,0,0,0
1291,41,447,5,3.0,2.0,85,4.0,2.0,2.0,6870,...,3,1.0,1.0,11,3,1.0,3,2,1,2
1045,34,1326,3,3.0,4.0,81,1.0,2.0,1.0,4759,...,3,4.0,1.0,15,2,3.0,13,9,3,12
847,32,862,2,1.0,3.0,76,3.0,1.0,1.0,2827,...,3,3.0,4.0,1,3,3.0,1,0,0,0
386,37,1107,14,3.0,4.0,95,3.0,1.0,1.0,3034,...,3,3.0,2.0,18,2,2.0,18,7,12,17
1254,31,1079,16,4.0,1.0,70,3.0,3.0,3.0,8161,...,3,1.0,4.0,10,2,3.0,1,0,0,0
557,38,268,2,5.0,4.0,92,3.0,1.0,3.0,3057,...,3,2.0,2.0,6,0,1.0,1,0,0,1
1293,30,1092,10,3.0,1.0,64,3.0,3.0,3.0,9667,...,3,2.0,1.0,9,3,3.0,7,7,0,2

In [57]:
data['PerformanceRating'] = data['PerformanceRating'].map({1: 1.0, 2: 2.0, 3: 3.0, 4: 4.0})
data.sample(10)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
354,30,641,25,2.0,4.0,85,3.0,2.0,3.0,4736,...,3.0,2.0,2.0,4,2,4.0,2,2,2,2
1104,38,888,10,4.0,3.0,71,3.0,2.0,3.0,6077,...,3.0,3.0,1.0,10,2,3.0,6,3,1,2
76,35,776,1,4.0,3.0,32,2.0,2.0,1.0,4312,...,3.0,2.0,1.0,16,2,3.0,15,13,2,8
599,40,720,16,4.0,1.0,51,2.0,2.0,3.0,5094,...,3.0,4.0,1.0,10,6,3.0,1,0,0,0
1366,47,1169,14,4.0,3.0,64,3.0,2.0,2.0,5467,...,3.0,3.0,2.0,16,4,4.0,8,7,1,7
480,34,254,1,2.0,2.0,83,2.0,1.0,4.0,3622,...,3.0,4.0,2.0,6,3,3.0,6,5,1,3
688,31,616,12,3.0,4.0,41,3.0,2.0,4.0,5855,...,3.0,3.0,3.0,10,2,1.0,9,7,8,5
1654,22,1256,3,4.0,3.0,48,2.0,1.0,4.0,2853,...,3.0,2.0,2.0,1,5,3.0,0,0,0,0
282,29,442,2,2.0,2.0,44,3.0,2.0,4.0,4554,...,3.0,1.0,1.0,10,3,2.0,10,7,0,9
1372,38,1206,9,2.0,2.0,71,3.0,1.0,4.0,4771,...,3.0,4.0,3.0,10,0,4.0,5,2,0,3

In [58]:
data['PerformanceRating'].unique()

array([3., 4.])

In [59]:
for col in data.columns:
    if (data[col].nunique() >= 7):
        print(f'{col:<{max_len}}: {data[col].nunique()}')

Age                     : 43
DailyRate               : 886
DistanceFromHome        : 29
HourlyRate              : 71
MonthlyIncome           : 1349
MonthlyRate             : 1427
NumCompaniesWorked      : 10
PercentSalaryHike       : 15
TotalWorkingYears       : 40
TrainingTimesLastYear   : 7
YearsAtCompany          : 37
YearsInCurrentRole      : 19
YearsSinceLastPromotion : 16
YearsWithCurrManager    : 18