In [108]:
import pandas as pd

In [109]:
data = pd.read_csv('watson_healthcare_modified.csv')
data.sample(4)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
131,1810635,50,No,Travel_Frequently,809,Cardiology,12,3,Marketing,1,...,4,80,0,16,3,3,2,2,2,1
305,1712914,36,No,Non-Travel,1105,Maternity,24,4,Life Sciences,1,...,3,80,1,11,3,3,9,8,0,8
1433,1104512,39,No,Non-Travel,105,Neurology,9,3,Life Sciences,1,...,3,80,0,21,3,2,6,0,1,3
1082,1827679,31,Yes,Travel_Frequently,561,Maternity,3,3,Life Sciences,1,...,1,80,0,7,2,1,7,2,7,7

In [110]:
data.shape

(1676, 35)

In [111]:
data.select_dtypes(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,No,Travel_Rarely,Cardiology,Life Sciences,Female,Nurse,Single,Y,Yes
1,No,Travel_Frequently,Maternity,Life Sciences,Male,Other,Married,Y,No
2,Yes,Travel_Rarely,Maternity,Other,Male,Nurse,Single,Y,Yes
3,No,Travel_Frequently,Maternity,Life Sciences,Female,Other,Married,Y,Yes
4,No,Travel_Rarely,Maternity,Medical,Male,Nurse,Married,Y,No
...,...,...,...,...,...,...,...,...,...
1671,Yes,Travel_Rarely,Neurology,Technical Degree,Male,Nurse,Single,Y,Yes
1672,No,Travel_Rarely,Cardiology,Marketing,Female,Nurse,Married,Y,Yes
1673,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
1674,No,Travel_Rarely,Neurology,Life Sciences,Female,Therapist,Married,Y,No
1675,No,Travel_Rarely,Cardiology,Medical,Female,Nurse,Single,Y,No

In [112]:
df = data.copy()
df.tail(5)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1671,1117656,26,Yes,Travel_Rarely,471,Neurology,24,3,Technical Degree,1,...,2,80,0,1,3,1,1,0,0,0
1672,1152327,46,No,Travel_Rarely,1125,Cardiology,10,3,Marketing,1,...,3,80,1,15,3,3,3,2,1,2
1673,1812428,20,No,Travel_Rarely,959,Maternity,1,3,Life Sciences,1,...,4,80,0,1,0,4,1,0,0,0
1674,1812429,39,No,Travel_Rarely,466,Neurology,1,1,Life Sciences,1,...,3,80,1,21,3,3,21,6,11,8
1675,1152329,27,No,Travel_Rarely,511,Cardiology,2,2,Medical,1,...,2,80,0,9,5,2,8,7,0,7

In [113]:
int64_df = df.select_dtypes(include='int64')
int64_df.columns

Index(['EmployeeID', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'Shift', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [114]:
del data # For original dataset safety

In [115]:
df = df.select_dtypes(include='object')
display(df.shape)
df.sample(4)

(1676, 9)

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
1013,Yes,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
40,No,Travel_Rarely,Maternity,Other,Male,Nurse,Divorced,Y,No
364,No,Travel_Rarely,Maternity,Medical,Female,Nurse,Married,Y,No
754,No,Travel_Rarely,Cardiology,Marketing,Male,Nurse,Divorced,Y,No

#### Dropping Over18 and EducationField

In [116]:
df.drop(columns=['Over18'], inplace=True)
df.sample(6)
display(df.shape)

(1676, 8)

In [117]:
from sklearn.preprocessing import OneHotEncoder

In [118]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='error', dtype='int64').set_output(transform='pandas')

### Encoding Objects to Numerical Values

#### Gender and Department encoding (ohe) and merging

In [119]:
enc_gender = ohe.fit_transform(df[['Gender']])
enc_department = ohe.fit_transform(df[['Department']])

In [120]:
enc_gender.sample(5)

      Gender_Female  Gender_Male
1152              0            1
314               0            1
527               1            0
1659              0            1
1655              1            0

In [121]:
enc_department.sample(4)

      Department_Cardiology  Department_Maternity  Department_Neurology
1304                      0                     0                     1
1520                      0                     0                     1
914                       1                     0                     0
738                       1                     0                     0

In [122]:
df = pd.concat([df, enc_department], axis=1).drop(columns=['Department'])
display(df.shape)
df.sample(5)

(1676, 10)

,Attrition,BusinessTravel,EducationField,Gender,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology
180,No,Travel_Rarely,Medical,Female,Other,Married,Yes,0,1,0
1497,No,Travel_Rarely,Life Sciences,Male,Nurse,Married,No,0,1,0
634,Yes,Travel_Frequently,Life Sciences,Female,Other,Divorced,Yes,0,1,0
1473,No,Travel_Frequently,Life Sciences,Male,Nurse,Married,No,0,1,0
319,No,Travel_Rarely,Technical Degree,Female,Nurse,Married,Yes,1,0,0

In [123]:
df = pd.concat([df, enc_gender], axis=1).drop(columns=['Gender'])
display(df.shape)
df.sample(7)

(1676, 11)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
730,No,Travel_Frequently,Medical,Nurse,Single,No,0,1,0,1,0
1066,No,Travel_Rarely,Life Sciences,Other,Divorced,No,0,1,0,0,1
1139,No,Travel_Rarely,Medical,Nurse,Single,Yes,0,1,0,1,0
1266,No,Travel_Rarely,Life Sciences,Other,Single,No,0,0,1,0,1
846,Yes,Travel_Rarely,Marketing,Nurse,Single,No,1,0,0,1,0
801,No,Non-Travel,Medical,Other,Single,No,0,0,1,0,1
829,No,Travel_Rarely,Medical,Nurse,Divorced,No,0,1,0,1,0

#### OverTime and Attrition encoding (mapping to 1s and 0s)

In [124]:
# yes = 1 | no = 0 
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})  
df['OverTime'] = df['OverTime'].map({'Yes': 1, 'No': 0})

In [125]:
df.head(3)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
0,0,Travel_Rarely,Life Sciences,Nurse,Single,1,1,0,0,1,0
1,0,Travel_Frequently,Life Sciences,Other,Married,0,0,1,0,0,1
2,1,Travel_Rarely,Other,Nurse,Single,1,0,1,0,0,1

#### Ordinal encoding for BusinessTravel and MaritalStatus

In [126]:
travel_frequency = ['Non-Travel', 'Travel_Rarely', 'Travel_Frequently'] # 0.0 = Non-Travel, 1.0 = Travel_Rarely, 2.0 = Travel_Frequently
marital_status = ['Single','Married', 'Divorced']

In [127]:
from sklearn.preprocessing import OrdinalEncoder

In [128]:
oe_travel = OrdinalEncoder(categories=[travel_frequency])
oe_marital_status = OrdinalEncoder(categories= [marital_status])

In [129]:
df['BusinessTravel'] = oe_travel.fit_transform(df[['BusinessTravel']]).astype('int64')

In [130]:
df['MaritalStatus'] = oe_marital_status.fit_transform(df[['MaritalStatus']]).astype('int64')

In [131]:
df.sample(10)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
814,0,0,Life Sciences,Therapist,0,0,0,1,0,0,1
79,0,1,Medical,Other,2,1,0,0,1,0,1
1124,0,1,Technical Degree,Other,1,0,0,1,0,0,1
700,0,1,Other,Nurse,2,0,1,0,0,0,1
879,0,1,Technical Degree,Therapist,2,1,0,0,1,1,0
1047,0,2,Medical,Nurse,0,0,0,1,0,1,0
1522,0,1,Medical,Therapist,1,0,0,1,0,1,0
192,1,1,Life Sciences,Therapist,1,1,0,1,0,0,1
996,0,1,Human Resources,Administrative,1,0,0,0,1,1,0
80,0,1,Life Sciences,Nurse,1,1,0,1,0,0,1

In [132]:
print(f'Attrition      = {df.Attrition.unique()}')
print(f'OverTime       = {df.OverTime.unique()}')
print(f'Gender         = {df.Gender_Male.unique()}')
print(f'Gender         = {df.Gender_Female.unique()}')
print(f'Department     = {df.Department_Cardiology.unique()}')
print(f'Department     = {df.Department_Maternity.unique()}')
print(f'Department     = {df.Department_Neurology.unique()}')
print(f'BusinessTravel = {df.BusinessTravel.unique()}')
print(f'MaritalStatus = {df.MaritalStatus.unique()}')
print(f'EducationField = {df.EducationField.unique()}')
print(f'JobRole        = {df.JobRole.unique()}')

Attrition      = [0 1]
OverTime       = [1 0]
Gender         = [0 1]
Gender         = [1 0]
Department     = [1 0]
Department     = [0 1]
Department     = [0 1]
BusinessTravel = [1 2 0]
MaritalStatus = [0 1 2]
EducationField = ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
JobRole        = ['Nurse' 'Other' 'Therapist' 'Administrative' 'Admin']

In [133]:
df[df['JobRole'] == 'Other'].count()

Attrition                534
BusinessTravel           534
EducationField           534
JobRole                  534
MaritalStatus            534
OverTime                 534
Department_Cardiology    534
Department_Maternity     534
Department_Neurology     534
Gender_Female            534
Gender_Male              534
dtype: int64

In [134]:
df[df['EducationField'] == 'Other'].count()

Attrition                88
BusinessTravel           88
EducationField           88
JobRole                  88
MaritalStatus            88
OverTime                 88
Department_Cardiology    88
Department_Maternity     88
Department_Neurology     88
Gender_Female            88
Gender_Male              88
dtype: int64

In [135]:
df.sample(7)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1237,0,0,Life Sciences,Nurse,1,1,0,1,0,0,1
1024,0,1,Life Sciences,Nurse,1,0,0,1,0,1,0
1532,0,2,Technical Degree,Other,0,0,0,1,0,1,0
486,0,1,Life Sciences,Nurse,1,0,0,1,0,1,0
78,0,1,Medical,Other,0,0,0,0,1,0,1
760,0,1,Life Sciences,Other,1,1,1,0,0,1,0
1589,0,1,Life Sciences,Nurse,1,1,0,1,0,0,1

#### JobRole and EducationField encoding (categorical mapping)

In [136]:
df['EducationField'] = df['EducationField'].map({'Other': 0, 'Life Sciences': 1, 'Medical': 2, 'Marketing': 3, 'Technical Degree': 4, 'Human Resources': 5})
df['is_other_JobRole'] = (df['JobRole'] == 'Other').astype(int)
df['JobRole'] = df['JobRole'].map({'Other': 0, 'Nurse': 1,'Therapist': 2, 'Administrative': 3, 'Admin': 4})

In [137]:
display(df.shape)
df.sample(10)

(1676, 12)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole
518,0,1,3,1,1,0,1,0,0,0,1,0
61,0,2,1,1,0,0,0,1,0,1,0,0
8,0,2,1,2,0,0,0,1,0,0,1,0
403,0,1,3,1,1,0,1,0,0,0,1,0
502,1,2,1,1,1,0,1,0,0,1,0,0
1246,1,1,3,0,0,0,1,0,0,1,0,1
365,0,0,2,2,1,0,0,0,1,1,0,0
1458,0,1,3,1,1,0,1,0,0,1,0,0
557,0,1,2,0,1,1,0,1,0,0,1,1
1013,1,1,1,0,0,0,0,1,0,1,0,1

In [138]:
df.isna().any()

Attrition                False
BusinessTravel           False
EducationField           False
JobRole                  False
MaritalStatus            False
OverTime                 False
Department_Cardiology    False
Department_Maternity     False
Department_Neurology     False
Gender_Female            False
Gender_Male              False
is_other_JobRole         False
dtype: bool