In [206]:
import pandas as pd

In [207]:
data = pd.read_csv('watson_healthcare_modified.csv')
data.sample(4)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1544,1159699,30,No,Travel_Rarely,201,Maternity,5,3,Technical Degree,1,...,4,80,1,8,3,3,3,2,2,2
1633,1698428,27,No,Travel_Rarely,975,Maternity,7,3,Medical,1,...,1,80,0,9,2,1,7,6,0,7
1399,1583381,39,No,Travel_Rarely,119,Cardiology,15,4,Marketing,1,...,1,80,0,21,3,3,20,8,11,10
264,1622255,28,Yes,Travel_Rarely,529,Maternity,2,4,Life Sciences,1,...,3,80,0,5,5,1,0,0,0,0

In [208]:
data.shape

(1676, 35)

In [209]:
data.select_dtypes(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,No,Travel_Rarely,Cardiology,Life Sciences,Female,Nurse,Single,Y,Yes
1,No,Travel_Frequently,Maternity,Life Sciences,Male,Other,Married,Y,No
2,Yes,Travel_Rarely,Maternity,Other,Male,Nurse,Single,Y,Yes
3,No,Travel_Frequently,Maternity,Life Sciences,Female,Other,Married,Y,Yes
4,No,Travel_Rarely,Maternity,Medical,Male,Nurse,Married,Y,No
...,...,...,...,...,...,...,...,...,...
1671,Yes,Travel_Rarely,Neurology,Technical Degree,Male,Nurse,Single,Y,Yes
1672,No,Travel_Rarely,Cardiology,Marketing,Female,Nurse,Married,Y,Yes
1673,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
1674,No,Travel_Rarely,Neurology,Life Sciences,Female,Therapist,Married,Y,No
1675,No,Travel_Rarely,Cardiology,Medical,Female,Nurse,Single,Y,No

In [210]:
df = data.copy()
df.tail(5)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1671,1117656,26,Yes,Travel_Rarely,471,Neurology,24,3,Technical Degree,1,...,2,80,0,1,3,1,1,0,0,0
1672,1152327,46,No,Travel_Rarely,1125,Cardiology,10,3,Marketing,1,...,3,80,1,15,3,3,3,2,1,2
1673,1812428,20,No,Travel_Rarely,959,Maternity,1,3,Life Sciences,1,...,4,80,0,1,0,4,1,0,0,0
1674,1812429,39,No,Travel_Rarely,466,Neurology,1,1,Life Sciences,1,...,3,80,1,21,3,3,21,6,11,8
1675,1152329,27,No,Travel_Rarely,511,Cardiology,2,2,Medical,1,...,2,80,0,9,5,2,8,7,0,7

In [211]:
del data # For original dataset safety

In [212]:
df = df.select_dtypes(include='object')
display(df.shape)
df.sample(4)

(1676, 9)

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
1588,No,Travel_Frequently,Maternity,Medical,Male,Other,Married,Y,Yes
7,No,Travel_Rarely,Maternity,Life Sciences,Male,Nurse,Divorced,Y,No
27,No,Travel_Rarely,Cardiology,Marketing,Male,Nurse,Married,Y,No
1643,No,Travel_Rarely,Maternity,Life Sciences,Female,Nurse,Single,Y,Yes

In [213]:
df.drop(columns=['Over18'], inplace=True)
df.sample(6)
display(df.shape)

(1676, 8)

In [214]:
from sklearn.preprocessing import OneHotEncoder

In [215]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='error', dtype='int64').set_output(transform='pandas')

### Encoding Objects to Numerical Values

#### Gender and Department encoding (ohe) and merging

In [216]:
enc_gender = ohe.fit_transform(df[['Gender']])
enc_department = ohe.fit_transform(df[['Department']])

In [217]:
enc_gender.sample(5)

      Gender_Female  Gender_Male
1114              0            1
691               0            1
1368              0            1
1018              0            1
1620              1            0

In [218]:
enc_department.sample(4)

      Department_Cardiology  Department_Maternity  Department_Neurology
1170                      0                     1                     0
766                       0                     1                     0
1324                      1                     0                     0
176                       0                     1                     0

In [219]:
df = pd.concat([df, enc_department], axis=1).drop(columns=['Department'])
display(df.shape)
df.sample(5)

(1676, 10)

,Attrition,BusinessTravel,EducationField,Gender,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology
1459,No,Non-Travel,Medical,Male,Therapist,Single,No,1,0,0
973,No,Travel_Rarely,Life Sciences,Male,Therapist,Married,Yes,0,1,0
1439,No,Travel_Rarely,Life Sciences,Male,Administrative,Married,No,0,0,1
894,No,Travel_Rarely,Life Sciences,Female,Nurse,Single,No,1,0,0
490,No,Travel_Rarely,Life Sciences,Female,Other,Married,No,0,0,1

In [220]:
df = pd.concat([df, enc_gender], axis=1).drop(columns=['Gender'])
display(df.shape)
df.sample(7)

(1676, 11)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
170,No,Travel_Rarely,Technical Degree,Other,Married,Yes,0,1,0,0,1
377,No,Travel_Rarely,Life Sciences,Other,Married,No,0,1,0,1,0
1262,No,Non-Travel,Technical Degree,Other,Divorced,No,0,1,0,0,1
1597,No,Travel_Frequently,Life Sciences,Nurse,Married,No,0,0,1,0,1
900,No,Travel_Rarely,Life Sciences,Nurse,Divorced,Yes,0,1,0,0,1
1488,No,Travel_Rarely,Life Sciences,Admin,Divorced,No,1,0,0,1,0
594,No,Travel_Rarely,Life Sciences,Other,Single,No,0,1,0,1,0

#### OverTime and Attrition encoding (mapping to 1s and 0s)

In [221]:
# yes = 1 | no = 0 
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})  
df['OverTime'] = df['OverTime'].map({'Yes': 1, 'No': 0})

In [222]:
df.head(3)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
0,0,Travel_Rarely,Life Sciences,Nurse,Single,1,1,0,0,1,0
1,0,Travel_Frequently,Life Sciences,Other,Married,0,0,1,0,0,1
2,1,Travel_Rarely,Other,Nurse,Single,1,0,1,0,0,1

#### Ordinal encoding for BusinessTravel and MaritalStatus

In [223]:
travel_frequency = ['Non-Travel', 'Travel_Rarely', 'Travel_Frequently'] # 0.0 = Non-Travel, 1.0 = Travel_Rarely, 2.0 = Travel_Frequently
marital_status = ['Single','Married', 'Divorced']

In [224]:
from sklearn.preprocessing import OrdinalEncoder

In [225]:
oe_travel = OrdinalEncoder(categories=[travel_frequency])
oe_marital_status = OrdinalEncoder(categories= [marital_status])

In [226]:
df['BusinessTravel'] = oe_travel.fit_transform(df[['BusinessTravel']]).astype('int64')

In [227]:
df['MaritalStatus'] = oe_marital_status.fit_transform(df[['MaritalStatus']]).astype('int64')

In [228]:
df.sample(10)

,Attrition,BusinessTravel,EducationField,JobRole,MaritalStatus,OverTime,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
283,0,1,Technical Degree,Nurse,1,1,0,1,0,0,1
1391,1,2,Marketing,Nurse,1,1,1,0,0,0,1
249,0,2,Life Sciences,Therapist,1,0,0,0,1,0,1
560,1,1,Other,Other,0,1,0,1,0,0,1
80,0,1,Life Sciences,Nurse,1,1,0,1,0,0,1
1227,0,1,Medical,Nurse,2,0,0,1,0,0,1
784,0,2,Life Sciences,Therapist,1,0,0,0,1,0,1
439,1,2,Human Resources,Other,2,1,0,0,1,1,0
467,0,1,Technical Degree,Other,2,1,0,1,0,0,1
1596,0,1,Medical,Nurse,1,0,0,0,1,1,0

In [231]:
print(f'Attrition      = {df.Attrition.unique()}')
print(f'OverTime       = {df.OverTime.unique()}')
print(f'Gender         = {df.Gender_Male.unique()}')
print(f'Gender         = {df.Gender_Female.unique()}')
print(f'Department     = {df.Department_Cardiology.unique()}')
print(f'Department     = {df.Department_Maternity.unique()}')
print(f'Department     = {df.Department_Neurology.unique()}')
print(f'BusinessTravel = {df.BusinessTravel.unique()}')
print(f'MaritalStatus = {df.MaritalStatus.unique()}')
print(f'EducationField = {df.EducationField.unique()}')
print(f'JobRole        = {df.JobRole.unique()}')

Attrition      = [0 1]
OverTime       = [1 0]
Gender         = [0 1]
Gender         = [1 0]
Department     = [1 0]
Department     = [0 1]
Department     = [0 1]
BusinessTravel = [1 2 0]
MaritalStatus = [0 1 2]
EducationField = ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
JobRole        = ['Nurse' 'Other' 'Therapist' 'Administrative' 'Admin']