## Data Preprocessing

In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv('watson_healthcare_modified.csv')
dataframe.sample(4)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
886,1362336,27,No,Travel_Rarely,1103,Maternity,14,3,Life Sciences,1,...,4,80,2,9,3,2,9,7,6,8
475,1875209,24,No,Travel_Rarely,823,Maternity,17,2,Other,1,...,4,80,1,1,2,3,1,0,0,0
95,1293078,54,No,Travel_Rarely,1217,Neurology,2,4,Technical Degree,1,...,1,80,1,16,5,1,4,3,0,3
418,1865341,26,No,Travel_Rarely,1349,Maternity,23,3,Life Sciences,1,...,2,80,2,3,3,1,3,2,0,2

In [3]:
dataframe.shape

(1676, 35)

In [4]:
dataframe.select_dtypes(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,No,Travel_Rarely,Cardiology,Life Sciences,Female,Nurse,Single,Y,Yes
1,No,Travel_Frequently,Maternity,Life Sciences,Male,Other,Married,Y,No
2,Yes,Travel_Rarely,Maternity,Other,Male,Nurse,Single,Y,Yes
3,No,Travel_Frequently,Maternity,Life Sciences,Female,Other,Married,Y,Yes
4,No,Travel_Rarely,Maternity,Medical,Male,Nurse,Married,Y,No
...,...,...,...,...,...,...,...,...,...
1671,Yes,Travel_Rarely,Neurology,Technical Degree,Male,Nurse,Single,Y,Yes
1672,No,Travel_Rarely,Cardiology,Marketing,Female,Nurse,Married,Y,Yes
1673,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
1674,No,Travel_Rarely,Neurology,Life Sciences,Female,Therapist,Married,Y,No
1675,No,Travel_Rarely,Cardiology,Medical,Female,Nurse,Single,Y,No

In [5]:
dframe = dataframe.copy()
dframe.tail(5)
del dataframe # For original dataset safety

### Train/Test Splitting

In [6]:
y = dframe['Attrition']
X = dframe.drop('Attrition', axis=1)

In [7]:
(dframe.dtypes).unique()
del dframe # Save memory

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [10]:
display(X_train.shape)
display(X_test.shape)
display(y_train.shape)
display(y_test.shape)

(1340, 34)

(336, 34)

(1340,)

(336,)

Encoding only the train sets to prevent data leakage

#### Attrition Mapping

In [11]:
# mapping attrition columns to 1s and 0s
y_test = y_test.map({'Yes': 1, 'No': 0})
y_train = y_train.map({'Yes': 1, 'No': 0})
display(y_test.head(7))
display(y_train.tail(7))

1260    0
709     1
261     0
107     1
1639    0
228     0
1226    0
Name: Attrition, dtype: int64

382     0
428     0
735     0
1350    1
71      0
320     0
552     0
Name: Attrition, dtype: int64

#### Test set unwanted feature deletion

In [12]:
EmployeeID_safe = X_test['EmployeeID']
dropping_columns = ['EmployeeID', 'Over18', 'EmployeeCount', 'StandardHours']
X_test.drop(dropping_columns, axis=1, inplace=True)
X_test.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1260,42,Travel_Rarely,855,Maternity,12,3,Medical,2,Male,57,...,4,2,3,7,6,2,5,3,0,4
709,29,Travel_Rarely,906,Maternity,10,3,Life Sciences,4,Female,92,...,4,3,0,3,5,3,0,0,0,0
261,38,Non-Travel,1327,Cardiology,2,2,Life Sciences,4,Male,39,...,3,4,1,13,0,3,8,7,7,5
107,25,Travel_Rarely,240,Cardiology,5,3,Marketing,3,Male,46,...,3,4,0,6,1,3,6,4,0,3
1639,29,Travel_Rarely,352,Neurology,6,1,Medical,4,Male,87,...,3,4,0,1,3,3,1,0,0,0

#### Train set unwanted feature deletion

In [13]:
X_train.drop(dropping_columns, axis=1, inplace=True)
X_train.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
417,40,Travel_Rarely,1398,Cardiology,2,4,Life Sciences,3,Female,79,...,3,4,0,21,2,3,20,15,1,12
243,40,Travel_Rarely,1300,Maternity,24,2,Technical Degree,1,Male,62,...,3,1,2,9,3,3,9,8,4,7
1628,25,Travel_Rarely,622,Cardiology,13,1,Medical,2,Male,40,...,3,3,0,7,1,3,7,4,0,6
454,33,Travel_Rarely,922,Maternity,1,5,Medical,1,Female,95,...,3,3,1,10,2,3,6,1,0,5
1532,39,Travel_Frequently,505,Maternity,2,4,Technical Degree,3,Female,64,...,4,4,0,20,1,3,19,6,11,8

In [14]:
X_train.select_dtypes(include='int64')

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
417,40,1398,2,4,3,79,3,5,3,18041,...,3,4,0,21,2,3,20,15,1,12
243,40,1300,24,2,1,62,3,2,4,3319,...,3,1,2,9,3,3,9,8,4,7
1628,25,622,13,1,2,40,3,1,3,2096,...,3,3,0,7,1,3,7,4,0,6
454,33,922,1,5,1,95,4,4,3,16184,...,3,3,1,10,2,3,6,1,0,5
1532,39,505,2,4,3,64,3,3,3,10938,...,4,4,0,20,1,3,19,6,11,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,41,549,7,2,4,42,3,2,3,5003,...,3,2,0,8,6,3,2,2,2,1
1350,56,1162,24,2,1,97,3,1,4,2587,...,3,4,0,5,3,3,4,2,1,0
71,29,1328,2,3,3,76,3,1,2,2703,...,4,4,1,6,3,3,5,4,0,4
320,27,1377,2,3,4,74,3,2,3,4478,...,3,1,0,5,3,3,5,4,0,4
552,27,975,7,3,4,55,2,2,1,6811,...,3,1,0,9,2,1,7,6,0,7

In [15]:
X_train.select_dtypes(include='object')

,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,OverTime
417,Travel_Rarely,Cardiology,Life Sciences,Female,Administrative,Married,No
243,Travel_Rarely,Maternity,Technical Degree,Male,Other,Divorced,No
1628,Travel_Rarely,Cardiology,Medical,Male,Other,Married,No
454,Travel_Rarely,Maternity,Medical,Female,Administrative,Divorced,No
1532,Travel_Frequently,Maternity,Technical Degree,Female,Other,Single,No
...,...,...,...,...,...,...,...
735,Travel_Rarely,Cardiology,Medical,Female,Therapist,Single,No
1350,Travel_Rarely,Neurology,Life Sciences,Male,Nurse,Single,No
71,Travel_Rarely,Maternity,Life Sciences,Male,Other,Married,No
320,Travel_Rarely,Cardiology,Life Sciences,Male,Nurse,Single,Yes
552,Travel_Rarely,Maternity,Medical,Female,Nurse,Single,No

### Encoding Objects to Numerical Values

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='error').set_output(transform='pandas')

#### Gender and Department encoding (ohe) and merging

In [18]:
enc_gender = ohe.fit_transform(X_train[['Gender']])
trans_gender = ohe.transform(X_test[['Gender']])
enc_department = ohe.fit_transform(X_train[['Department']])
trans_department = ohe.transform(X_test[['Department']])

In [19]:
display(enc_gender.sample(5))
display(trans_gender.sample(5))

     Gender_Female  Gender_Male
970            1.0          0.0
772            0.0          1.0
109            1.0          0.0
842            1.0          0.0
416            0.0          1.0

      Gender_Female  Gender_Male
1308            1.0          0.0
683             0.0          1.0
1409            0.0          1.0
1386            0.0          1.0
1005            1.0          0.0

In [20]:
display(enc_department.sample(4))
display(trans_department.sample(4))

     Department_Cardiology  Department_Maternity  Department_Neurology
5                      0.0                   1.0                   0.0
55                     0.0                   0.0                   1.0
705                    0.0                   1.0                   0.0
631                    0.0                   0.0                   1.0

      Department_Cardiology  Department_Maternity  Department_Neurology
107                     1.0                   0.0                   0.0
881                     1.0                   0.0                   0.0
1095                    0.0                   1.0                   0.0
1586                    1.0                   0.0                   0.0

In [21]:
X_train = pd.concat([X_train, enc_department], axis=1).drop(columns=['Department'])
X_test = pd.concat([X_test, trans_department], axis=1).drop(columns=['Department'])
print(f'Test Set: {X_test.shape}')
display(X_test.sample(5))
print(f'Train Set: {X_train.shape}')
display(X_train.sample(5))

Test Set: (336, 32)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology
174,45,Travel_Rarely,1268,4,2,Life Sciences,3,Female,30,3,...,9,3,4,5,4,0,3,1.0,0.0,0.0
230,52,Travel_Rarely,1323,2,3,Life Sciences,3,Female,89,2,...,6,3,2,2,2,2,2,0.0,1.0,0.0
172,36,Travel_Frequently,1480,3,2,Medical,4,Male,30,3,...,13,3,2,8,7,7,2,0.0,1.0,0.0
1362,39,Non-Travel,1251,21,4,Life Sciences,1,Female,32,1,...,10,1,3,3,2,1,2,1.0,0.0,0.0
981,28,Travel_Rarely,736,26,3,Life Sciences,3,Male,48,2,...,5,0,3,5,3,0,4,1.0,0.0,0.0

Train Set: (1340, 32)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology
645,35,Travel_Rarely,672,25,3,Technical Degree,4,Male,78,2,...,16,2,3,13,10,4,8,0.0,1.0,0.0
1184,38,Travel_Frequently,1189,1,3,Life Sciences,4,Male,90,3,...,19,4,4,13,11,2,9,0.0,1.0,0.0
1186,33,Travel_Rarely,392,2,4,Medical,4,Male,93,3,...,6,5,3,6,2,0,4,1.0,0.0,0.0
877,32,Travel_Frequently,116,13,3,Other,3,Female,77,2,...,2,2,3,2,2,2,2,0.0,1.0,0.0
1387,38,Travel_Rarely,1404,1,3,Life Sciences,1,Male,59,2,...,20,3,2,1,0,0,0,1.0,0.0,0.0

In [22]:
X_train = pd.concat([X_train, enc_gender], axis=1).drop(columns=['Gender'])
X_test = pd.concat([X_test, trans_gender], axis=1).drop(columns=['Gender'])
print(f'Test Set: {X_test.shape}')
display(X_test.sample(5))
print(f'Train Set: {X_train.shape}')
display(X_train.sample(5))

Test Set: (336, 33)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
911,55,Non-Travel,177,8,1,Medical,4,37,2,4,...,3,33,9,15,0,0.0,1.0,0.0,0.0,1.0
1614,52,Non-Travel,585,29,4,Life Sciences,1,40,3,1,...,2,9,8,0,0,1.0,0.0,0.0,0.0,1.0
668,27,Travel_Rarely,618,4,3,Life Sciences,2,76,3,1,...,3,1,1,0,0,0.0,1.0,0.0,1.0,0.0
944,52,Travel_Rarely,1030,5,3,Life Sciences,2,64,3,3,...,2,8,7,7,7,1.0,0.0,0.0,0.0,1.0
1204,55,Travel_Rarely,1441,22,3,Technical Degree,1,94,2,1,...,3,4,2,1,2,0.0,1.0,0.0,0.0,1.0

Train Set: (1340, 33)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
676,48,Travel_Rarely,1469,20,4,Medical,4,51,3,1,...,2,0,0,0,0,0.0,1.0,0.0,0.0,1.0
116,34,Travel_Rarely,1354,5,3,Medical,3,45,2,3,...,3,11,10,5,8,0.0,0.0,1.0,1.0,0.0
351,32,Travel_Rarely,1062,2,3,Medical,3,75,3,1,...,3,8,0,0,7,0.0,1.0,0.0,1.0,0.0
1201,48,Travel_Frequently,708,7,2,Medical,4,95,3,1,...,3,9,7,7,7,1.0,0.0,0.0,1.0,0.0
181,34,Travel_Rarely,629,27,2,Medical,4,95,3,1,...,3,3,2,1,2,0.0,1.0,0.0,1.0,0.0

#### OverTime encoding (mapping to 1s and 0s)

In [23]:
X_train['OverTime']

417      No
243      No
1628     No
454      No
1532     No
       ...
735      No
1350     No
71       No
320     Yes
552      No
Name: OverTime, Length: 1340, dtype: object

In [24]:
# yes = 1 | no = 0  
X_train['OverTime'] = X_train['OverTime'].map({'Yes': 1, 'No': 0})
X_test['OverTime'] = X_test['OverTime'].map({'Yes': 1, 'No': 0})

In [25]:
display(X_train.head(7))
display(X_test.head(7))

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
417,40,Travel_Rarely,1398,2,4,Life Sciences,3,79,3,5,...,3,20,15,1,12,1.0,0.0,0.0,1.0,0.0
243,40,Travel_Rarely,1300,24,2,Technical Degree,1,62,3,2,...,3,9,8,4,7,0.0,1.0,0.0,0.0,1.0
1628,25,Travel_Rarely,622,13,1,Medical,2,40,3,1,...,3,7,4,0,6,1.0,0.0,0.0,0.0,1.0
454,33,Travel_Rarely,922,1,5,Medical,1,95,4,4,...,3,6,1,0,5,0.0,1.0,0.0,1.0,0.0
1532,39,Travel_Frequently,505,2,4,Technical Degree,3,64,3,3,...,3,19,6,11,8,0.0,1.0,0.0,1.0,0.0
331,27,Non-Travel,210,1,1,Marketing,3,73,3,2,...,3,5,4,1,4,1.0,0.0,0.0,0.0,1.0
1110,32,Non-Travel,1200,1,4,Technical Degree,4,62,3,2,...,2,6,5,1,2,0.0,1.0,0.0,0.0,1.0

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1260,42,Travel_Rarely,855,12,3,Medical,2,57,3,1,...,2,5,3,0,4,0.0,1.0,0.0,0.0,1.0
709,29,Travel_Rarely,906,10,3,Life Sciences,4,92,2,1,...,3,0,0,0,0,0.0,1.0,0.0,1.0,0.0
261,38,Non-Travel,1327,2,2,Life Sciences,4,39,2,2,...,3,8,7,7,5,1.0,0.0,0.0,0.0,1.0
107,25,Travel_Rarely,240,5,3,Marketing,3,46,2,2,...,3,6,4,0,3,1.0,0.0,0.0,0.0,1.0
1639,29,Travel_Rarely,352,6,1,Medical,4,87,2,1,...,3,1,0,0,0,0.0,0.0,1.0,0.0,1.0
228,35,Travel_Frequently,944,1,3,Marketing,3,92,3,3,...,4,10,7,0,8,1.0,0.0,0.0,1.0,0.0
1226,40,Travel_Rarely,369,8,2,Life Sciences,2,92,3,2,...,3,1,0,0,0,0.0,1.0,0.0,1.0,0.0

#### Ordinal encoding for BusinessTravel and MaritalStatus

In [26]:
travel_frequency = ['Non-Travel', 'Travel_Rarely', 'Travel_Frequently'] # 0.0 = Non-Travel, 1.0 = Travel_Rarely, 2.0 = Travel_Frequently
marital_status = ['Single','Married', 'Divorced']

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [28]:
oe_travel = OrdinalEncoder(categories=[travel_frequency])
oe_marital_status = OrdinalEncoder(categories= [marital_status])

In [29]:
X_train['BusinessTravel'] = oe_travel.fit_transform(X_train[['BusinessTravel']])
X_test['BusinessTravel'] = oe_travel.transform(X_test[['BusinessTravel']])

In [30]:
X_train['MaritalStatus'] = oe_marital_status.fit_transform(X_train[['MaritalStatus']])
X_test['MaritalStatus'] = oe_marital_status.transform(X_test[['MaritalStatus']])

In [31]:
display((X_train[['BusinessTravel','MaritalStatus']]).sample(7))
display((X_test[['BusinessTravel','MaritalStatus']]).sample(7))

      BusinessTravel  MaritalStatus
1269             1.0            1.0
292              2.0            2.0
1512             1.0            1.0
1146             1.0            2.0
1581             0.0            1.0
847              0.0            2.0
701              0.0            0.0

      BusinessTravel  MaritalStatus
881              1.0            2.0
783              0.0            1.0
734              1.0            0.0
1065             2.0            0.0
640              1.0            1.0
287              1.0            2.0
752              1.0            1.0

In [32]:
max_len = max(len(col) for col in X_train.columns) # finds the length of the largest column name

for col in X_train.columns:
    print(f'{col:<{max_len}} = {X_train[col].nunique()}') # left aligns the column name

Age                      = 43
BusinessTravel           = 3
DailyRate                = 793
DistanceFromHome         = 29
Education                = 5
EducationField           = 6
EnvironmentSatisfaction  = 4
HourlyRate               = 71
JobInvolvement           = 4
JobLevel                 = 5
JobRole                  = 5
JobSatisfaction          = 4
MaritalStatus            = 3
MonthlyIncome            = 1134
MonthlyRate              = 1191
NumCompaniesWorked       = 10
OverTime                 = 2
PercentSalaryHike        = 15
PerformanceRating        = 2
RelationshipSatisfaction = 4
Shift                    = 4
TotalWorkingYears        = 40
TrainingTimesLastYear    = 7
WorkLifeBalance          = 4
YearsAtCompany           = 37
YearsInCurrentRole       = 19
YearsSinceLastPromotion  = 16
YearsWithCurrManager     = 18
Department_Cardiology    = 2
Department_Maternity     = 2
Department_Neurology     = 2
Gender_Female            = 2
Gender_Male              = 2

In [33]:
display((X_train['JobRole'] == 'Other').sum())
display((X_test['JobRole'] == 'Other').sum())

np.int64(434)

np.int64(100)

In [34]:
display((X_train['EducationField'] == 'Other').sum())
display((X_test['EducationField'] == 'Other').sum())

np.int64(75)

np.int64(13)

In [35]:
display((X_train['OverTime'] == 1).sum())
display((X_test['OverTime'] == 1).sum())

np.int64(386)

np.int64(90)

In [36]:
display((y_train == 1).sum())
display((y_test == 1).sum())

np.int64(159)

np.int64(40)

In [37]:
X_train.sample(7)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
769,56,2.0,1240,9,3,Medical,1,63,3,1,...,3,5,4,0,3,0.0,1.0,0.0,1.0,0.0
1035,48,1.0,1221,7,3,Marketing,3,96,3,2,...,3,2,2,2,2,1.0,0.0,0.0,0.0,1.0
1168,40,1.0,1329,7,3,Life Sciences,1,73,3,1,...,1,4,2,0,3,0.0,1.0,0.0,0.0,1.0
1497,45,1.0,192,10,2,Life Sciences,1,69,3,1,...,2,2,2,0,2,0.0,1.0,0.0,0.0,1.0
1082,31,2.0,561,3,3,Life Sciences,4,33,3,1,...,1,7,2,7,7,0.0,1.0,0.0,1.0,0.0
1505,40,1.0,369,8,2,Life Sciences,2,92,3,2,...,3,1,0,0,0,0.0,1.0,0.0,1.0,0.0
34,24,1.0,813,1,3,Medical,2,61,3,1,...,2,2,0,2,0,0.0,1.0,0.0,0.0,1.0

In [38]:
X_test.sample(7)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
335,40,1.0,1124,1,2,Medical,2,57,1,2,...,2,4,3,0,2,1.0,0.0,0.0,0.0,1.0
1319,46,1.0,706,2,2,Life Sciences,4,82,3,3,...,2,9,8,4,7,1.0,0.0,0.0,0.0,1.0
732,22,1.0,217,8,1,Life Sciences,2,94,1,1,...,2,4,3,1,1,0.0,1.0,0.0,0.0,1.0
1609,36,2.0,1302,6,4,Life Sciences,1,80,4,2,...,3,3,2,0,2,0.0,0.0,1.0,0.0,1.0
788,35,1.0,1204,4,3,Technical Degree,4,86,3,3,...,3,8,7,4,7,1.0,0.0,0.0,0.0,1.0
709,29,1.0,906,10,3,Life Sciences,4,92,2,1,...,3,0,0,0,0,0.0,1.0,0.0,1.0,0.0
154,32,2.0,967,8,3,Marketing,2,43,3,3,...,3,9,8,3,7,1.0,0.0,0.0,1.0,0.0

#### JobRole and EducationField encoding (categorical mapping)

In [39]:
X_train['EducationField'] = X_train['EducationField'].map({'Other': 0, 'Life Sciences': 1, 'Medical': 2, 'Marketing': 3, 'Technical Degree': 4, 'Human Resources': 5})
X_train['is_other_JobRole'] = (X_train['JobRole'] == 'Other').astype(int)
X_train['JobRole'] = X_train['JobRole'].map({'Other': 0, 'Nurse': 1,'Therapist': 2, 'Administrative': 3, 'Admin': 4})

In [40]:
(X_train[['EducationField','is_other_JobRole','JobRole']]).sample(5)

      EducationField  is_other_JobRole  JobRole
1110               4                 1        0
499                2                 1        0
1020               1                 1        0
130                2                 1        0
1150               2                 1        0

In [41]:
X_test['EducationField'] = X_test['EducationField'].map({'Other': 0, 'Life Sciences': 1, 'Medical': 2, 'Marketing': 3, 'Technical Degree': 4, 'Human Resources': 5})
X_test['is_other_JobRole'] = (X_test['JobRole'] == 'Other').astype(int)
X_test['JobRole'] = X_test['JobRole'].map({'Other': 0, 'Nurse': 1,'Therapist': 2, 'Administrative': 3, 'Admin': 4})

In [42]:
(X_test[['EducationField','is_other_JobRole','JobRole']]).sample(5)

      EducationField  is_other_JobRole  JobRole
1046               1                 0        1
1586               1                 0        1
956                1                 1        0
1012               0                 1        0
376                1                 0        1

In [43]:
X_train.dtypes

Age                           int64
BusinessTravel              float64
DailyRate                     int64
DistanceFromHome              int64
Education                     int64
EducationField                int64
EnvironmentSatisfaction       int64
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                       int64
JobSatisfaction               int64
MaritalStatus               float64
MonthlyIncome                 int64
MonthlyRate                   int64
NumCompaniesWorked            int64
OverTime                      int64
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
Shift                         int64
TotalWorkingYears             int64
TrainingTimesLastYear         int64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion       int64
YearsWithCurrManager          int64
Department_Cardiology       float64
Department_Maternity        float64
Department_Neurology        float64
Gender_Female               float64
Gender_Male                 float64
is_other_JobRole              int64
dtype: object

In [44]:
X_test.dtypes

Age                           int64
BusinessTravel              float64
DailyRate                     int64
DistanceFromHome              int64
Education                     int64
EducationField                int64
EnvironmentSatisfaction       int64
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                       int64
JobSatisfaction               int64
MaritalStatus               float64
MonthlyIncome                 int64
MonthlyRate                   int64
NumCompaniesWorked            int64
OverTime                      int64
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
Shift                         int64
TotalWorkingYears             int64
TrainingTimesLastYear         int64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion       int64
YearsWithCurrManager          int64
Department_Cardiology       float64
Department_Maternity        float64
Department_Neurology        float64
Gender_Female               float64
Gender_Male                 float64
is_other_JobRole              int64
dtype: object

In [45]:
# checking all the dtypes are equal in  train and test sets
display((X_train.dtypes == X_test.dtypes).any() )
display(y_train.dtype == y_test.dtype)

np.True_

True

In [46]:
display(X_train.shape)
display(X_test.shape)

(1340, 34)

(336, 34)

In [47]:
X_train.isna().any().any()

np.False_

In [48]:
X_test.isna().any().any()

np.False_

In [49]:
X_test.columns

Index(['Age', 'BusinessTravel', 'DailyRate', 'DistanceFromHome', 'Education',
       'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'Shift', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'Department_Cardiology', 'Department_Maternity', 'Department_Neurology',
       'Gender_Female', 'Gender_Male', 'is_other_JobRole'],
      dtype='object')

In [50]:
X_test.shape

(336, 34)

### Combining Train Cases to train_set and Test Cases to test_set

In [51]:
train_set = pd.concat([X_train, y_train], axis=1)
display(train_set.shape)
train_set.head()

(1340, 35)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole,Attrition
417,40,1.0,1398,2,4,1,3,79,3,5,...,15,1,12,1.0,0.0,0.0,1.0,0.0,0,0
243,40,1.0,1300,24,2,4,1,62,3,2,...,8,4,7,0.0,1.0,0.0,0.0,1.0,1,0
1628,25,1.0,622,13,1,2,2,40,3,1,...,4,0,6,1.0,0.0,0.0,0.0,1.0,1,0
454,33,1.0,922,1,5,2,1,95,4,4,...,1,0,5,0.0,1.0,0.0,1.0,0.0,0,0
1532,39,2.0,505,2,4,4,3,64,3,3,...,6,11,8,0.0,1.0,0.0,1.0,0.0,1,0

In [52]:
test_set = pd.concat([X_test, y_test], axis=1)
display(test_set.shape)
test_set.head()

(336, 35)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole,Attrition
1260,42,1.0,855,12,3,2,2,57,3,1,...,3,0,4,0.0,1.0,0.0,0.0,1.0,0,0
709,29,1.0,906,10,3,1,4,92,2,1,...,0,0,0,0.0,1.0,0.0,1.0,0.0,1,1
261,38,0.0,1327,2,2,1,4,39,2,2,...,7,7,5,1.0,0.0,0.0,0.0,1.0,0,0
107,25,1.0,240,5,3,3,3,46,2,2,...,4,0,3,1.0,0.0,0.0,0.0,1.0,0,1
1639,29,1.0,352,6,1,2,4,87,2,1,...,0,0,0,0.0,0.0,1.0,0.0,1.0,1,0

In [53]:
train_set.to_csv('train_set_datasheet.csv', index=False)
test_set.to_csv('test_set_datasheet.csv', index=False)

## Cross Validation

In [54]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [55]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

### CV with Logistic Regression Model

In [56]:
import warnings
warnings.filterwarnings('ignore')

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
lr = LogisticRegression(max_iter=500, random_state=42)

lr_scores = cross_val_score(
    lr,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'LR CV ROC-AUC: {lr_scores}')
print(f'Mean ROC-AUC : {lr_scores.mean()}\n\nRounded ROC-AUC: {round(lr_scores.mean(), 3)} ')

LR CV ROC-AUC: [0.88335375 0.87182203 0.89141949 0.82719809 0.89764301]
Mean ROC-AUC : 0.8742872753897014

Rounded ROC-AUC: 0.874

### CV with Random Forest Classifier

In [59]:
from sklearn.ensemble import RandomForestClassifier

In [60]:
rf = RandomForestClassifier(n_estimators=200, random_state=42)

rf_scores = cross_val_score(
    rf,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'RF CV ROC-AUC: {rf_scores}')
print(f'Mean ROC-AUC : {rf_scores.mean()}\n\nRounded ROC-AUC: {round(rf_scores.mean(), 3)} ')

RF CV ROC-AUC: [0.9475296  0.9357786  0.94286282 0.93299788 0.92750265]
Mean ROC-AUC : 0.9373343106145018

Rounded ROC-AUC: 0.937

### CV with Gradient Boosting Classifier

In [61]:
from sklearn.ensemble import GradientBoostingClassifier

In [62]:
gb = GradientBoostingClassifier(random_state=42)

gb_scores = cross_val_score(
    gb,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'GB CV ROC-AUC: {gb_scores}')
print(f'Mean ROC-AUC : {gb_scores.mean()}\n\nRounded ROC-AUC: {round(gb_scores.mean(), 3)} ')

GB CV ROC-AUC: [0.9508643  0.94637182 0.96305614 0.95762712 0.92412606]
Mean ROC-AUC : 0.9484090884841733

Rounded ROC-AUC: 0.948

### CV with XGBoost

In [63]:
from xgboost import XGBClassifier

In [64]:
xgb = XGBClassifier(
    n_estimators=200,        # not too large
    learning_rate=0.05,      # LOWER than default
    max_depth=3,             # very important (reduce)
    min_child_weight=5,      # prevents small leaf splits
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.5,           # L1 regularization
    reg_lambda=1.0,          # L2 regularization
    eval_metric="logloss",
    random_state=42
)


xgb_scores = cross_val_score(
    xgb,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'GB CV ROC-AUC: {xgb_scores}')
print(f'Mean ROC-AUC : {xgb_scores.mean()}\n\nRounded ROC-AUC: {round(xgb_scores.mean(), 3)} ')

GB CV ROC-AUC: [0.96025589 0.95855403 0.95286017 0.95286017 0.94756356]
Mean ROC-AUC : 0.9544187620970627

Rounded ROC-AUC: 0.954

In [65]:
# xgb = XGBClassifier(
#     n_estimators=200,
#     learning_rate=0.1,
#     max_depth=5,
#     subsample=0.8,
#     colsample_bytree=0.8,
#     eval_metric='logloss',
#     random_state=42
# )

In [66]:
# <model>  : <ROC-AUC value>
LR_Score = round(lr_scores.mean(), 3)
RF_Score = round(rf_scores.mean(), 3)
GB_Score = round(gb_scores.mean(), 3)
XGB_Score = round(xgb_scores.mean(), 3)

In [67]:
Scores = {'Logistic Regression': LR_Score, 'Random Forest Classifier': RF_Score, 'Gradient Boosting Classifier': GB_Score, 'XGBoost': XGB_Score}
models = {'Logistic Regression': lr, 'Random Forest Classifier': rf, 'Gradient Boosting Classifier': gb, 'XGBoost': xgb}

best_model_name = max(Scores, key=Scores.get)
best_model = models[best_model_name]

print(f'The Best Model for Training is {best_model_name}')

The Best Model for Training is XGBoost

## Training Model

In [68]:
best_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [69]:
from sklearn.metrics import roc_auc_score

In [70]:
y_test_proba = best_model.predict_proba(X_test)[:, 1]
print(f'Test set ROC-AUC: {round(roc_auc_score(y_test, y_test_proba), 3)}')

Test set ROC-AUC: 0.927

In [71]:
def risk_pred(p):
    if (p < 0.25):
        return 'most likely to stay'
    elif (p >= 0.25 and p < 0.50):
        return 'likely to stay'
    elif (p >= 0.50 and p < 0.75):
        return 'likely to leave'
    else:
        return 'most likely to leave'

In [72]:
# dataset with EmployeeID
EmployeeID_dataset = pd.concat([EmployeeID_safe, X_test], axis=1)
del EmployeeID_safe
display(EmployeeID_dataset.shape)
EmployeeID_dataset.head()

(336, 35)

,EmployeeID,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole
1260,1628396,42,1.0,855,12,3,2,2,57,3,...,5,3,0,4,0.0,1.0,0.0,0.0,1.0,0
709,1658398,29,1.0,906,10,3,1,4,92,2,...,0,0,0,0,0.0,1.0,0.0,1.0,0.0,1
261,1520532,38,0.0,1327,2,2,1,4,39,2,...,8,7,7,5,1.0,0.0,0.0,0.0,1.0,0
107,1410589,25,1.0,240,5,3,3,3,46,2,...,6,4,0,3,1.0,0.0,0.0,0.0,1.0,0
1639,1309082,29,1.0,352,6,1,2,4,87,2,...,1,0,0,0,0.0,0.0,1.0,0.0,1.0,1

In [73]:
results = pd.DataFrame({
    'PersonID': EmployeeID_dataset['EmployeeID'],   
    'Attrition_Probability': y_test_proba,
    'Predicted_Risk': [risk_pred(p) for p in y_test_proba],
    'Actual_Attrition': y_test.values
})

In [74]:
results.sample(10)

      PersonID  Attrition_Probability       Predicted_Risk  Actual_Attrition
1579   1157111               0.013520  most likely to stay                 0
972    1081600               0.389234       likely to stay                 1
100    1843825               0.212048  most likely to stay                 1
1530   1252790               0.011470  most likely to stay                 0
620    1119237               0.003530  most likely to stay                 0
1096   1044155               0.012041  most likely to stay                 0
809    1789769               0.009772  most likely to stay                 0
108    1657986               0.015878  most likely to stay                 0
1410   1811717               0.039305  most likely to stay                 0
614    1455518               0.007791  most likely to stay                 0

In [75]:
from sklearn.metrics import accuracy_score

In [76]:
y_pred_binary = (y_test_proba >= 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred_binary)

print(f'Accuracy: {round(accuracy, 3)}')

Accuracy: 0.932

### Model Evaluation

In [77]:
from sklearn.metrics import classification_report, confusion_matrix

In [78]:
print(f'\n=== {best_model_name} Evaluation ===\n')

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_binary))

print('\nClassification Report:')
print(classification_report(y_test, y_pred_binary))

=== XGBoost Evaluation ===

Confusion Matrix:
[[293   3]
 [ 20  20]]

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       296
           1       0.87      0.50      0.63        40

    accuracy                           0.93       336
   macro avg       0.90      0.74      0.80       336
weighted avg       0.93      0.93      0.92       336

## Avoiding Overfitting With Undersampling

In [79]:
from imblearn.under_sampling import RandomUnderSampler

In [80]:
rus = RandomUnderSampler(random_state=42)

In [81]:
# fitting the train set to the under sampler
X_res_train, y_res_train = rus.fit_resample(X_train, y_train)

## Cross Validation for Resampled data

In [82]:
del best_model # save memory

### Resampled CV Logistic Regression

In [83]:
lr_scores = cross_val_score(
    lr,
    X_res_train,
    y_res_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'LR CV ROC-AUC: {lr_scores}')
print(f'Mean ROC-AUC : {lr_scores.mean()}\n\nRounded ROC-AUC: {round(lr_scores.mean(), 3)} ')

LR CV ROC-AUC: [0.86035156 0.93359375 0.80078125 0.84778226 0.86189516]
Mean ROC-AUC : 0.8608807963709676

Rounded ROC-AUC: 0.861

### Resampled CV Random Forest Classifier

In [84]:
rf_scores = cross_val_score(
    rf,
    X_res_train,
    y_res_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'RF CV ROC-AUC: {rf_scores}')
print(f'Mean ROC-AUC : {rf_scores.mean()}\n\nRounded ROC-AUC: {round(rf_scores.mean(), 3)} ')

RF CV ROC-AUC: [0.92333984 0.93945312 0.94580078 0.89516129 0.94808468]
Mean ROC-AUC : 0.930367943548387

Rounded ROC-AUC: 0.93

### Resampled CV Gradient Boosting Classifier

In [85]:
gb_scores = cross_val_score(
    gb,
    X_res_train,
    y_res_train,
    cv=cv,
    scoring='roc_auc'
)


print(f'GB CV ROC-AUC: {gb_scores}')
print(f'Mean ROC-AUC : {gb_scores.mean()}\n\nRounded ROC-AUC: {round(gb_scores.mean(), 3)} ')

GB CV ROC-AUC: [0.9140625  0.93945312 0.9375     0.88104839 0.94354839]
Mean ROC-AUC : 0.9231224798387097

Rounded ROC-AUC: 0.923

### Resampled CV XGBoost

In [86]:
xgb = XGBClassifier(
    n_estimators=200,        # not too large
    learning_rate=0.05,      # LOWER than default
    max_depth=3,             # very important (reduce)
    min_child_weight=5,      # prevents small leaf splits
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.5,           # L1 regularization
    reg_lambda=1.0,          # L2 regularization
    eval_metric="logloss",
    random_state=42
)

xgb_scores = cross_val_score(
    xgb,
    X_res_train,
    y_res_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'GB CV ROC-AUC: {gb_scores}')
print(f'Mean ROC-AUC : {gb_scores.mean()}\n\nRounded ROC-AUC: {round(gb_scores.mean(), 3)} ')

GB CV ROC-AUC: [0.9140625  0.93945312 0.9375     0.88104839 0.94354839]
Mean ROC-AUC : 0.9231224798387097

Rounded ROC-AUC: 0.923

In [87]:
LR_Score = round(lr_scores.mean(), 3)
RF_Score = round(rf_scores.mean(), 3)
GB_Score = round(gb_scores.mean(), 3)
XGB_Score = round(xgb_scores.mean(), 3)

In [88]:
Scores = {'Logistic Regression': LR_Score, 'Random Forest Classifier': RF_Score, 'Gradient Boosting Classifier': GB_Score, 'XGBoost': XGB_Score}
models = {'Logistic Regression': lr, 'Random Forest Classifier': rf, 'Gradient Boosting Classifier': gb, 'XGBoost': xgb}

best_model_name = max(Scores, key=Scores.get)
best_resampled_model = models[best_model_name]

print(f'The Best Model for Training is {best_model_name}')

The Best Model for Training is XGBoost

In [89]:
best_resampled_model.fit(X_res_train, y_res_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [90]:
y_test_proba = best_resampled_model.predict_proba(X_test)[:, 1]
print(f'Test set ROC-AUC: {round(roc_auc_score(y_test, y_test_proba), 3)}')

Test set ROC-AUC: 0.928

In [91]:
results.sample(10)

      PersonID  Attrition_Probability        Predicted_Risk  Actual_Attrition
314    1536502               0.014370   most likely to stay                 0
920    1488640               0.001613   most likely to stay                 0
1265   1473417               0.032244   most likely to stay                 0
911    1364438               0.010763   most likely to stay                 0
1160   1552731               0.020713   most likely to stay                 0
262    1593179               0.022773   most likely to stay                 0
637    1127921               0.001311   most likely to stay                 0
963    1536328               0.036461   most likely to stay                 1
1479   1308741               0.002148   most likely to stay                 0
1329   1329673               0.983680  most likely to leave                 1

In [92]:
y_pred_binary = (y_test_proba >= 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred_binary)

print(f'Accuracy: {round(accuracy, 3)}')

Accuracy: 0.881

In [93]:
print(f'\n=== {best_model_name} Evaluation with Resampled Train-Set ===\n')

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_binary))

print('\nClassification Report:')
print(classification_report(y_test, y_pred_binary))

=== XGBoost Evaluation with Resampled Train-Set ===

Confusion Matrix:
[[262  34]
 [  6  34]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.89      0.93       296
           1       0.50      0.85      0.63        40

    accuracy                           0.88       336
   macro avg       0.74      0.87      0.78       336
weighted avg       0.92      0.88      0.89       336

In [94]:
# Train (RESAMPLED)
y_train_res_proba = best_resampled_model.predict_proba(X_res_train)[:, 1]
train_auc = roc_auc_score(y_res_train, y_train_res_proba)

# Test (ORIGINAL, untouched)
y_test_proba = best_resampled_model.predict_proba(X_test)[:, 1]
test_auc = roc_auc_score(y_test, y_test_proba)

print("Train ROC-AUC (resampled):", round(train_auc, 3))
print("Test ROC-AUC:", round(test_auc, 3))

Train ROC-AUC (resampled): 0.991
Test ROC-AUC: 0.928