## Data Preprocessing

In [309]:
import pandas as pd

In [310]:
dataframe = pd.read_csv('watson_healthcare_modified.csv')
dataframe.sample(4)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
191,1155351,27,No,Travel_Rarely,894,Maternity,9,3,Medical,1,...,4,80,0,7,2,2,7,7,0,3
1163,1533221,48,No,Travel_Frequently,365,Neurology,4,5,Medical,1,...,2,80,1,23,3,3,2,2,2,2
1297,1645498,34,No,Travel_Rarely,810,Cardiology,8,2,Technical Degree,1,...,3,80,2,10,5,3,10,8,4,8
507,1179356,33,No,Travel_Frequently,1296,Maternity,6,3,Life Sciences,1,...,3,80,1,15,2,1,13,11,4,7

In [311]:
dataframe.shape

(1676, 35)

In [312]:
dataframe.select_dtypes(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,No,Travel_Rarely,Cardiology,Life Sciences,Female,Nurse,Single,Y,Yes
1,No,Travel_Frequently,Maternity,Life Sciences,Male,Other,Married,Y,No
2,Yes,Travel_Rarely,Maternity,Other,Male,Nurse,Single,Y,Yes
3,No,Travel_Frequently,Maternity,Life Sciences,Female,Other,Married,Y,Yes
4,No,Travel_Rarely,Maternity,Medical,Male,Nurse,Married,Y,No
...,...,...,...,...,...,...,...,...,...
1671,Yes,Travel_Rarely,Neurology,Technical Degree,Male,Nurse,Single,Y,Yes
1672,No,Travel_Rarely,Cardiology,Marketing,Female,Nurse,Married,Y,Yes
1673,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
1674,No,Travel_Rarely,Neurology,Life Sciences,Female,Therapist,Married,Y,No
1675,No,Travel_Rarely,Cardiology,Medical,Female,Nurse,Single,Y,No

In [313]:
dframe = dataframe.copy()
dframe.tail(5)
del dataframe # For original dataset safety

### Train/Test Splitting

In [314]:
y = dframe['Attrition']
X = dframe.drop('Attrition', axis=1)

In [315]:
(dframe.dtypes).unique()
del dframe # Save memory

In [316]:
from sklearn.model_selection import train_test_split

In [317]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [318]:
display(X_train.shape)
display(X_test.shape)
display(y_train.shape)
display(y_test.shape)

(1340, 34)

(336, 34)

(1340,)

(336,)

Encoding only the train sets to prevent data leakage

#### Attrition Mapping

In [319]:
# mapping attrition columns to 1s and 0s
y_test = y_test.map({'Yes': 1, 'No': 0})
y_train = y_train.map({'Yes': 1, 'No': 0})
display(y_test.head(7))
display(y_train.tail(7))

1260    0
709     1
261     0
107     1
1639    0
228     0
1226    0
Name: Attrition, dtype: int64

382     0
428     0
735     0
1350    1
71      0
320     0
552     0
Name: Attrition, dtype: int64

#### Test set unwanted feature deletion

In [320]:
EmployeeID_safe = X_test['EmployeeID']
dropping_columns = ['EmployeeID', 'Over18', 'EmployeeCount', 'StandardHours']
X_test.drop(dropping_columns, axis=1, inplace=True)
X_test.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1260,42,Travel_Rarely,855,Maternity,12,3,Medical,2,Male,57,...,4,2,3,7,6,2,5,3,0,4
709,29,Travel_Rarely,906,Maternity,10,3,Life Sciences,4,Female,92,...,4,3,0,3,5,3,0,0,0,0
261,38,Non-Travel,1327,Cardiology,2,2,Life Sciences,4,Male,39,...,3,4,1,13,0,3,8,7,7,5
107,25,Travel_Rarely,240,Cardiology,5,3,Marketing,3,Male,46,...,3,4,0,6,1,3,6,4,0,3
1639,29,Travel_Rarely,352,Neurology,6,1,Medical,4,Male,87,...,3,4,0,1,3,3,1,0,0,0

#### Train set unwanted feature deletion

In [321]:
X_train.drop(dropping_columns, axis=1, inplace=True)
X_train.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
417,40,Travel_Rarely,1398,Cardiology,2,4,Life Sciences,3,Female,79,...,3,4,0,21,2,3,20,15,1,12
243,40,Travel_Rarely,1300,Maternity,24,2,Technical Degree,1,Male,62,...,3,1,2,9,3,3,9,8,4,7
1628,25,Travel_Rarely,622,Cardiology,13,1,Medical,2,Male,40,...,3,3,0,7,1,3,7,4,0,6
454,33,Travel_Rarely,922,Maternity,1,5,Medical,1,Female,95,...,3,3,1,10,2,3,6,1,0,5
1532,39,Travel_Frequently,505,Maternity,2,4,Technical Degree,3,Female,64,...,4,4,0,20,1,3,19,6,11,8

In [322]:
X_train.select_dtypes(include='int64')

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
417,40,1398,2,4,3,79,3,5,3,18041,...,3,4,0,21,2,3,20,15,1,12
243,40,1300,24,2,1,62,3,2,4,3319,...,3,1,2,9,3,3,9,8,4,7
1628,25,622,13,1,2,40,3,1,3,2096,...,3,3,0,7,1,3,7,4,0,6
454,33,922,1,5,1,95,4,4,3,16184,...,3,3,1,10,2,3,6,1,0,5
1532,39,505,2,4,3,64,3,3,3,10938,...,4,4,0,20,1,3,19,6,11,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,41,549,7,2,4,42,3,2,3,5003,...,3,2,0,8,6,3,2,2,2,1
1350,56,1162,24,2,1,97,3,1,4,2587,...,3,4,0,5,3,3,4,2,1,0
71,29,1328,2,3,3,76,3,1,2,2703,...,4,4,1,6,3,3,5,4,0,4
320,27,1377,2,3,4,74,3,2,3,4478,...,3,1,0,5,3,3,5,4,0,4
552,27,975,7,3,4,55,2,2,1,6811,...,3,1,0,9,2,1,7,6,0,7

In [323]:
X_train.select_dtypes(include='object')

,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,OverTime
417,Travel_Rarely,Cardiology,Life Sciences,Female,Administrative,Married,No
243,Travel_Rarely,Maternity,Technical Degree,Male,Other,Divorced,No
1628,Travel_Rarely,Cardiology,Medical,Male,Other,Married,No
454,Travel_Rarely,Maternity,Medical,Female,Administrative,Divorced,No
1532,Travel_Frequently,Maternity,Technical Degree,Female,Other,Single,No
...,...,...,...,...,...,...,...
735,Travel_Rarely,Cardiology,Medical,Female,Therapist,Single,No
1350,Travel_Rarely,Neurology,Life Sciences,Male,Nurse,Single,No
71,Travel_Rarely,Maternity,Life Sciences,Male,Other,Married,No
320,Travel_Rarely,Cardiology,Life Sciences,Male,Nurse,Single,Yes
552,Travel_Rarely,Maternity,Medical,Female,Nurse,Single,No

### Encoding Objects to Numerical Values

In [324]:
from sklearn.preprocessing import OneHotEncoder

In [325]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='error').set_output(transform='pandas')

#### Gender and Department encoding (ohe) and merging

In [326]:
enc_gender = ohe.fit_transform(X_train[['Gender']])
trans_gender = ohe.transform(X_test[['Gender']])
enc_department = ohe.fit_transform(X_train[['Department']])
trans_department = ohe.transform(X_test[['Department']])

In [327]:
display(enc_gender.sample(5))
display(trans_gender.sample(5))

      Gender_Female  Gender_Male
1073            1.0          0.0
291             0.0          1.0
684             0.0          1.0
441             0.0          1.0
352             1.0          0.0

      Gender_Female  Gender_Male
262             0.0          1.0
1616            1.0          0.0
757             1.0          0.0
733             0.0          1.0
1163            0.0          1.0

In [328]:
display(enc_department.sample(4))
display(trans_department.sample(4))

      Department_Cardiology  Department_Maternity  Department_Neurology
41                      0.0                   1.0                   0.0
1104                    0.0                   0.0                   1.0
127                     1.0                   0.0                   0.0
538                     0.0                   1.0                   0.0

      Department_Cardiology  Department_Maternity  Department_Neurology
1164                    1.0                   0.0                   0.0
1665                    0.0                   0.0                   1.0
327                     1.0                   0.0                   0.0
511                     0.0                   1.0                   0.0

In [329]:
X_train = pd.concat([X_train, enc_department], axis=1).drop(columns=['Department'])
X_test = pd.concat([X_test, trans_department], axis=1).drop(columns=['Department'])
print(f'Test Set: {X_test.shape}')
display(X_test.sample(5))
print(f'Train Set: {X_train.shape}')
display(X_train.sample(5))

Test Set: (336, 32)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology
577,34,Travel_Rarely,121,2,4,Medical,3,Female,86,2,...,6,3,3,6,5,1,3,0.0,1.0,0.0
624,32,Travel_Rarely,638,8,2,Medical,3,Female,91,4,...,9,3,2,5,3,1,3,0.0,1.0,0.0
1540,45,Non-Travel,1195,2,2,Medical,1,Male,65,2,...,22,1,3,20,8,11,8,0.0,1.0,0.0
614,51,Travel_Rarely,1318,26,4,Marketing,1,Female,66,3,...,29,2,2,20,6,4,17,1.0,0.0,0.0
683,26,Travel_Frequently,1283,1,3,Medical,3,Male,52,2,...,7,2,3,7,7,0,7,1.0,0.0,0.0

Train Set: (1340, 32)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology
10,35,Travel_Rarely,809,16,3,Medical,1,Male,84,4,...,6,5,3,5,4,0,3,0.0,1.0,0.0
1195,33,Non-Travel,530,16,3,Life Sciences,3,Female,36,3,...,7,2,3,6,5,1,2,1.0,0.0,0.0
1130,43,Travel_Rarely,990,27,3,Technical Degree,4,Male,87,4,...,8,0,3,6,4,0,2,0.0,1.0,0.0
1380,34,Travel_Rarely,937,1,3,Marketing,1,Male,32,3,...,14,3,2,14,8,2,1,1.0,0.0,0.0
94,32,Travel_Rarely,1093,6,4,Medical,2,Male,87,3,...,12,0,3,11,8,5,7,1.0,0.0,0.0

In [330]:
X_train = pd.concat([X_train, enc_gender], axis=1).drop(columns=['Gender'])
X_test = pd.concat([X_test, trans_gender], axis=1).drop(columns=['Gender'])
print(f'Test Set: {X_test.shape}')
display(X_test.sample(5))
print(f'Train Set: {X_train.shape}')
display(X_train.sample(5))

Test Set: (336, 33)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
734,48,Travel_Rarely,1355,4,4,Life Sciences,3,78,2,3,...,3,15,11,4,8,0.0,1.0,0.0,0.0,1.0
549,39,Travel_Rarely,141,3,3,Human Resources,3,44,4,2,...,1,8,3,3,6,0.0,0.0,1.0,1.0,0.0
237,52,Non-Travel,771,2,4,Life Sciences,1,79,2,5,...,4,33,7,15,12,1.0,0.0,0.0,0.0,1.0
327,39,Travel_Rarely,1162,3,2,Medical,4,41,3,2,...,2,1,0,0,0,1.0,0.0,0.0,1.0,0.0
855,53,Travel_Rarely,1223,7,2,Medical,4,50,3,5,...,3,7,7,4,7,0.0,0.0,1.0,1.0,0.0

Train Set: (1340, 33)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
877,32,Travel_Frequently,116,13,3,Other,3,77,2,1,...,3,2,2,2,2,0.0,1.0,0.0,1.0,0.0
943,40,Travel_Rarely,299,25,4,Marketing,4,57,2,3,...,3,5,4,1,0,1.0,0.0,0.0,0.0,1.0
1538,53,Travel_Rarely,102,23,4,Life Sciences,4,72,3,4,...,3,12,9,3,8,0.0,0.0,1.0,1.0,0.0
110,51,Travel_Frequently,1456,1,4,Medical,1,30,2,3,...,2,13,12,12,8,0.0,1.0,0.0,1.0,0.0
1188,31,Travel_Rarely,1112,5,4,Life Sciences,1,67,3,2,...,3,10,0,0,2,1.0,0.0,0.0,1.0,0.0

#### OverTime encoding (mapping to 1s and 0s)

In [331]:
X_train['OverTime']

417      No
243      No
1628     No
454      No
1532     No
       ...
735      No
1350     No
71       No
320     Yes
552      No
Name: OverTime, Length: 1340, dtype: object

In [332]:
# yes = 1 | no = 0  
X_train['OverTime'] = X_train['OverTime'].map({'Yes': 1, 'No': 0})
X_test['OverTime'] = X_test['OverTime'].map({'Yes': 1, 'No': 0})

In [333]:
display(X_train.head(7))
display(X_test.head(7))

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
417,40,Travel_Rarely,1398,2,4,Life Sciences,3,79,3,5,...,3,20,15,1,12,1.0,0.0,0.0,1.0,0.0
243,40,Travel_Rarely,1300,24,2,Technical Degree,1,62,3,2,...,3,9,8,4,7,0.0,1.0,0.0,0.0,1.0
1628,25,Travel_Rarely,622,13,1,Medical,2,40,3,1,...,3,7,4,0,6,1.0,0.0,0.0,0.0,1.0
454,33,Travel_Rarely,922,1,5,Medical,1,95,4,4,...,3,6,1,0,5,0.0,1.0,0.0,1.0,0.0
1532,39,Travel_Frequently,505,2,4,Technical Degree,3,64,3,3,...,3,19,6,11,8,0.0,1.0,0.0,1.0,0.0
331,27,Non-Travel,210,1,1,Marketing,3,73,3,2,...,3,5,4,1,4,1.0,0.0,0.0,0.0,1.0
1110,32,Non-Travel,1200,1,4,Technical Degree,4,62,3,2,...,2,6,5,1,2,0.0,1.0,0.0,0.0,1.0

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1260,42,Travel_Rarely,855,12,3,Medical,2,57,3,1,...,2,5,3,0,4,0.0,1.0,0.0,0.0,1.0
709,29,Travel_Rarely,906,10,3,Life Sciences,4,92,2,1,...,3,0,0,0,0,0.0,1.0,0.0,1.0,0.0
261,38,Non-Travel,1327,2,2,Life Sciences,4,39,2,2,...,3,8,7,7,5,1.0,0.0,0.0,0.0,1.0
107,25,Travel_Rarely,240,5,3,Marketing,3,46,2,2,...,3,6,4,0,3,1.0,0.0,0.0,0.0,1.0
1639,29,Travel_Rarely,352,6,1,Medical,4,87,2,1,...,3,1,0,0,0,0.0,0.0,1.0,0.0,1.0
228,35,Travel_Frequently,944,1,3,Marketing,3,92,3,3,...,4,10,7,0,8,1.0,0.0,0.0,1.0,0.0
1226,40,Travel_Rarely,369,8,2,Life Sciences,2,92,3,2,...,3,1,0,0,0,0.0,1.0,0.0,1.0,0.0

#### Ordinal encoding for BusinessTravel and MaritalStatus

In [334]:
travel_frequency = ['Non-Travel', 'Travel_Rarely', 'Travel_Frequently'] # 0.0 = Non-Travel, 1.0 = Travel_Rarely, 2.0 = Travel_Frequently
marital_status = ['Single','Married', 'Divorced']

In [335]:
from sklearn.preprocessing import OrdinalEncoder

In [336]:
oe_travel = OrdinalEncoder(categories=[travel_frequency])
oe_marital_status = OrdinalEncoder(categories= [marital_status])

In [337]:
X_train['BusinessTravel'] = oe_travel.fit_transform(X_train[['BusinessTravel']])
X_test['BusinessTravel'] = oe_travel.transform(X_test[['BusinessTravel']])

In [338]:
X_train['MaritalStatus'] = oe_marital_status.fit_transform(X_train[['MaritalStatus']])
X_test['MaritalStatus'] = oe_marital_status.transform(X_test[['MaritalStatus']])

In [339]:
display((X_train[['BusinessTravel','MaritalStatus']]).sample(7))
display((X_test[['BusinessTravel','MaritalStatus']]).sample(7))

      BusinessTravel  MaritalStatus
1244             1.0            1.0
619              1.0            1.0
1360             2.0            1.0
324              1.0            1.0
647              1.0            0.0
1497             1.0            1.0
1291             1.0            0.0

      BusinessTravel  MaritalStatus
799              2.0            1.0
1411             0.0            2.0
511              1.0            0.0
1282             0.0            0.0
185              1.0            1.0
1345             1.0            2.0
1546             1.0            2.0

In [340]:
max_len = max(len(col) for col in X_train.columns) # finds the length of the largest column name

for col in X_train.columns:
    print(f'{col:<{max_len}} = {X_train[col].nunique()}') # left aligns the column name

Age                      = 43
BusinessTravel           = 3
DailyRate                = 793
DistanceFromHome         = 29
Education                = 5
EducationField           = 6
EnvironmentSatisfaction  = 4
HourlyRate               = 71
JobInvolvement           = 4
JobLevel                 = 5
JobRole                  = 5
JobSatisfaction          = 4
MaritalStatus            = 3
MonthlyIncome            = 1134
MonthlyRate              = 1191
NumCompaniesWorked       = 10
OverTime                 = 2
PercentSalaryHike        = 15
PerformanceRating        = 2
RelationshipSatisfaction = 4
Shift                    = 4
TotalWorkingYears        = 40
TrainingTimesLastYear    = 7
WorkLifeBalance          = 4
YearsAtCompany           = 37
YearsInCurrentRole       = 19
YearsSinceLastPromotion  = 16
YearsWithCurrManager     = 18
Department_Cardiology    = 2
Department_Maternity     = 2
Department_Neurology     = 2
Gender_Female            = 2
Gender_Male              = 2

In [341]:
display((X_train['JobRole'] == 'Other').sum())
display((X_test['JobRole'] == 'Other').sum())

np.int64(434)

np.int64(100)

In [342]:
display((X_train['EducationField'] == 'Other').sum())
display((X_test['EducationField'] == 'Other').sum())

np.int64(75)

np.int64(13)

In [343]:
display((X_train['OverTime'] == 1).sum())
display((X_test['OverTime'] == 1).sum())

np.int64(386)

np.int64(90)

In [344]:
display((y_train == 1).sum())
display((y_test == 1).sum())

np.int64(159)

np.int64(40)

In [345]:
X_train.sample(7)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1200,53,1.0,1395,24,4,Medical,2,48,4,3,...,3,4,3,1,2,0.0,1.0,0.0,0.0,1.0
164,27,0.0,1450,3,3,Medical,3,79,2,1,...,2,1,1,0,1,0.0,1.0,0.0,0.0,1.0
48,46,2.0,1211,5,4,Marketing,1,98,3,2,...,3,9,6,0,8,1.0,0.0,0.0,0.0,1.0
965,36,2.0,607,7,3,Marketing,1,83,4,2,...,2,15,7,6,13,1.0,0.0,0.0,1.0,0.0
1537,48,1.0,163,2,5,Marketing,2,37,3,2,...,3,9,7,6,7,1.0,0.0,0.0,1.0,0.0
584,24,0.0,1092,9,3,Life Sciences,3,60,2,1,...,3,1,0,0,0,0.0,1.0,0.0,0.0,1.0
1536,31,1.0,1154,2,2,Life Sciences,1,54,3,1,...,3,2,2,1,2,1.0,0.0,0.0,0.0,1.0

In [346]:
X_test.sample(7)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1161,40,1.0,448,16,3,Life Sciences,3,84,3,3,...,2,4,2,3,3,0.0,1.0,0.0,1.0,0.0
1414,38,2.0,508,6,4,Life Sciences,1,72,2,2,...,3,8,3,7,7,1.0,0.0,0.0,0.0,1.0
1163,48,2.0,365,4,5,Medical,3,89,2,4,...,3,2,2,2,2,0.0,0.0,1.0,0.0,1.0
577,34,1.0,121,2,4,Medical,3,86,2,1,...,3,6,5,1,3,0.0,1.0,0.0,1.0,0.0
1457,50,1.0,410,28,3,Marketing,4,39,2,3,...,3,3,2,2,0,1.0,0.0,0.0,0.0,1.0
1313,43,2.0,1422,2,4,Life Sciences,1,92,3,2,...,3,7,7,7,7,1.0,0.0,0.0,0.0,1.0
26,32,2.0,1125,16,1,Life Sciences,2,72,1,1,...,3,10,2,6,7,0.0,1.0,0.0,1.0,0.0

#### JobRole and EducationField encoding (categorical mapping)

In [347]:
X_train['EducationField'] = X_train['EducationField'].map({'Other': 0, 'Life Sciences': 1, 'Medical': 2, 'Marketing': 3, 'Technical Degree': 4, 'Human Resources': 5})
X_train['is_other_JobRole'] = (X_train['JobRole'] == 'Other').astype(int)
X_train['JobRole'] = X_train['JobRole'].map({'Other': 0, 'Nurse': 1,'Therapist': 2, 'Administrative': 3, 'Admin': 4})

In [348]:
(X_train[['EducationField','is_other_JobRole','JobRole']]).sample(5)

      EducationField  is_other_JobRole  JobRole
91                 3                 0        1
636                3                 0        1
1436               1                 0        2
1271               3                 0        1
541                2                 0        1

In [349]:
X_test['EducationField'] = X_test['EducationField'].map({'Other': 0, 'Life Sciences': 1, 'Medical': 2, 'Marketing': 3, 'Technical Degree': 4, 'Human Resources': 5})
X_test['is_other_JobRole'] = (X_test['JobRole'] == 'Other').astype(int)
X_test['JobRole'] = X_test['JobRole'].map({'Other': 0, 'Nurse': 1,'Therapist': 2, 'Administrative': 3, 'Admin': 4})

In [350]:
(X_test[['EducationField','is_other_JobRole','JobRole']]).sample(5)

      EducationField  is_other_JobRole  JobRole
1510               1                 0        1
997                0                 0        1
231                4                 1        0
1362               1                 0        1
780                4                 1        0

In [351]:
X_train.dtypes

Age                           int64
BusinessTravel              float64
DailyRate                     int64
DistanceFromHome              int64
Education                     int64
EducationField                int64
EnvironmentSatisfaction       int64
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                       int64
JobSatisfaction               int64
MaritalStatus               float64
MonthlyIncome                 int64
MonthlyRate                   int64
NumCompaniesWorked            int64
OverTime                      int64
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
Shift                         int64
TotalWorkingYears             int64
TrainingTimesLastYear         int64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion       int64
YearsWithCurrManager          int64
Department_Cardiology       float64
Department_Maternity        float64
Department_Neurology        float64
Gender_Female               float64
Gender_Male                 float64
is_other_JobRole              int64
dtype: object

In [352]:
X_test.dtypes

Age                           int64
BusinessTravel              float64
DailyRate                     int64
DistanceFromHome              int64
Education                     int64
EducationField                int64
EnvironmentSatisfaction       int64
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                       int64
JobSatisfaction               int64
MaritalStatus               float64
MonthlyIncome                 int64
MonthlyRate                   int64
NumCompaniesWorked            int64
OverTime                      int64
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
Shift                         int64
TotalWorkingYears             int64
TrainingTimesLastYear         int64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion       int64
YearsWithCurrManager          int64
Department_Cardiology       float64
Department_Maternity        float64
Department_Neurology        float64
Gender_Female               float64
Gender_Male                 float64
is_other_JobRole              int64
dtype: object

In [353]:
# checking all the dtypes are equal in  train and test sets
display((X_train.dtypes == X_test.dtypes).any() )
display(y_train.dtype == y_test.dtype)

np.True_

True

In [354]:
display(X_train.shape)
display(X_test.shape)

(1340, 34)

(336, 34)

In [355]:
X_train.isna().any().any()

np.False_

In [356]:
X_test.isna().any().any()

np.False_

In [357]:
X_test.columns

Index(['Age', 'BusinessTravel', 'DailyRate', 'DistanceFromHome', 'Education',
       'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'Shift', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'Department_Cardiology', 'Department_Maternity', 'Department_Neurology',
       'Gender_Female', 'Gender_Male', 'is_other_JobRole'],
      dtype='object')

In [358]:
X_test.shape

(336, 34)

### Combining Train Cases to train_set and Test Cases to test_set

In [359]:
train_set = pd.concat([X_train, y_train], axis=1)
display(train_set.shape)
train_set.head()

(1340, 35)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole,Attrition
417,40,1.0,1398,2,4,1,3,79,3,5,...,15,1,12,1.0,0.0,0.0,1.0,0.0,0,0
243,40,1.0,1300,24,2,4,1,62,3,2,...,8,4,7,0.0,1.0,0.0,0.0,1.0,1,0
1628,25,1.0,622,13,1,2,2,40,3,1,...,4,0,6,1.0,0.0,0.0,0.0,1.0,1,0
454,33,1.0,922,1,5,2,1,95,4,4,...,1,0,5,0.0,1.0,0.0,1.0,0.0,0,0
1532,39,2.0,505,2,4,4,3,64,3,3,...,6,11,8,0.0,1.0,0.0,1.0,0.0,1,0

In [360]:
test_set = pd.concat([X_test, y_test], axis=1)
display(test_set.shape)
test_set.head()

(336, 35)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole,Attrition
1260,42,1.0,855,12,3,2,2,57,3,1,...,3,0,4,0.0,1.0,0.0,0.0,1.0,0,0
709,29,1.0,906,10,3,1,4,92,2,1,...,0,0,0,0.0,1.0,0.0,1.0,0.0,1,1
261,38,0.0,1327,2,2,1,4,39,2,2,...,7,7,5,1.0,0.0,0.0,0.0,1.0,0,0
107,25,1.0,240,5,3,3,3,46,2,2,...,4,0,3,1.0,0.0,0.0,0.0,1.0,0,1
1639,29,1.0,352,6,1,2,4,87,2,1,...,0,0,0,0.0,0.0,1.0,0.0,1.0,1,0

In [361]:
train_set.to_csv('train_set_datasheet.csv', index=False)
test_set.to_csv('test_set_datasheet.csv', index=False)

## Cross Validation

In [362]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [363]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

### CV with Logistic Regression Model

In [364]:
import warnings
warnings.filterwarnings('ignore')

In [365]:
from sklearn.linear_model import LogisticRegression

In [366]:
lr = LogisticRegression(max_iter=500, random_state=42)

lr_scores = cross_val_score(
    lr,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'LR CV ROC-AUC: {lr_scores}')
print(f'Mean ROC-AUC : {lr_scores.mean()}\n\nRounded ROC-AUC: {round(lr_scores.mean(), 3)} ')

LR CV ROC-AUC: [0.88335375 0.87182203 0.89141949 0.82719809 0.89764301]
Mean ROC-AUC : 0.8742872753897014

Rounded ROC-AUC: 0.874

### CV with Random Forest Classifier

In [367]:
from sklearn.ensemble import RandomForestClassifier

In [368]:
rf = RandomForestClassifier(n_estimators=200, random_state=42)

rf_scores = cross_val_score(
    rf,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'RF CV ROC-AUC: {rf_scores}')
print(f'Mean ROC-AUC : {rf_scores.mean()}\n\nRounded ROC-AUC: {round(rf_scores.mean(), 3)} ')

RF CV ROC-AUC: [0.9475296  0.9357786  0.94286282 0.93299788 0.92750265]
Mean ROC-AUC : 0.9373343106145018

Rounded ROC-AUC: 0.937

### CV with Gradient Boosting Classifier

In [369]:
from sklearn.ensemble import GradientBoostingClassifier

In [370]:
gb = GradientBoostingClassifier(random_state=42)

gb_scores = cross_val_score(
    gb,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'GB CV ROC-AUC: {gb_scores}')
print(f'Mean ROC-AUC : {gb_scores.mean()}\n\nRounded ROC-AUC: {round(gb_scores.mean(), 3)} ')

GB CV ROC-AUC: [0.9508643  0.94637182 0.96305614 0.95762712 0.92412606]
Mean ROC-AUC : 0.9484090884841733

Rounded ROC-AUC: 0.948

### CV with XGBoost

In [371]:
from xgboost import XGBClassifier

In [372]:
xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss',
    random_state=42
)

xgb_scores = cross_val_score(
    xgb,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'GB CV ROC-AUC: {xgb_scores}')
print(f'Mean ROC-AUC : {xgb_scores.mean()}\n\nRounded ROC-AUC: {round(xgb_scores.mean(), 3)} ')

GB CV ROC-AUC: [0.95385872 0.95021186 0.96080508 0.9470339  0.94239936]
Mean ROC-AUC : 0.950861785941685

Rounded ROC-AUC: 0.951

In [373]:
# <model>  : <ROC-AUC value>
LR_Score = round(lr_scores.mean(), 3)
RF_Score = round(rf_scores.mean(), 3)
GB_Score = round(gb_scores.mean(), 3)
XGB_Score = round(xgb_scores.mean(), 3)

In [374]:
Scores = {'Logistic Regression': LR_Score, 'Random Forest Classifier': RF_Score, 'Gradient Boosting Classifier': GB_Score, 'XGBoost': XGB_Score}
models = {'Logistic Regression': lr, 'Random Forest Classifier': rf, 'Gradient Boosting Classifier': gb, 'XGBoost': xgb}

best_model_name = max(Scores, key=Scores.get)
best_model = models[best_model_name]

print(f'The Best Model for Training is {best_model_name}')

The Best Model for Training is XGBoost

## Training Model

In [375]:
best_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [376]:
from sklearn.metrics import roc_auc_score

In [377]:
y_test_proba = best_model.predict_proba(X_test)[:, 1]
print(f'Test set ROC-AUC: {round(roc_auc_score(y_test, y_test_proba), 3)}')

Test set ROC-AUC: 0.915

In [378]:
def risk_pred(p):
    if (p < 0.25):
        return 'most likely to stay'
    elif (p >= 0.25 and p < 0.50):
        return 'likely to stay'
    elif (p >= 0.50 and p < 0.75):
        return 'likely to leave'
    else:
        return 'most likely to leave'

In [379]:
# dataset with EmployeeID
EmployeeID_dataset = pd.concat([EmployeeID_safe, X_test], axis=1)
del EmployeeID_safe
display(EmployeeID_dataset.shape)
EmployeeID_dataset.head()

(336, 35)

,EmployeeID,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole
1260,1628396,42,1.0,855,12,3,2,2,57,3,...,5,3,0,4,0.0,1.0,0.0,0.0,1.0,0
709,1658398,29,1.0,906,10,3,1,4,92,2,...,0,0,0,0,0.0,1.0,0.0,1.0,0.0,1
261,1520532,38,0.0,1327,2,2,1,4,39,2,...,8,7,7,5,1.0,0.0,0.0,0.0,1.0,0
107,1410589,25,1.0,240,5,3,3,3,46,2,...,6,4,0,3,1.0,0.0,0.0,0.0,1.0,0
1639,1309082,29,1.0,352,6,1,2,4,87,2,...,1,0,0,0,0.0,0.0,1.0,0.0,1.0,1

In [380]:
results = pd.DataFrame({
    'PersonID': EmployeeID_dataset['EmployeeID'],   
    'Attrition_Probability': y_test_proba,
    'Predicted_Risk': [risk_pred(p) for p in y_test_proba],
    'Actual_Attrition': y_test.values
})

In [381]:
results.sample(10)

      PersonID  Attrition_Probability       Predicted_Risk  Actual_Attrition
23     1880078               0.372562       likely to stay                 0
820    1377897               0.000628  most likely to stay                 0
174    1319352               0.000082  most likely to stay                 0
731    1824641               0.000060  most likely to stay                 0
437    1204541               0.020266  most likely to stay                 0
972    1081600               0.146104  most likely to stay                 1
783    1169735               0.004051  most likely to stay                 0
739    1509823               0.008325  most likely to stay                 0
1285   1083173               0.000010  most likely to stay                 0
391    1488170               0.000418  most likely to stay                 0

In [382]:
from sklearn.metrics import accuracy_score

In [383]:
y_pred_binary = (y_test_proba >= 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred_binary)

print(f'Accuracy: {round(accuracy, 3)}')

Accuracy: 0.917

### Model Evaluation

In [384]:
from sklearn.metrics import classification_report, confusion_matrix

In [385]:
print(f'\n=== {best_model_name} Evaluation ===\n')

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_binary))

print('\nClassification Report:')
print(classification_report(y_test, y_pred_binary))

=== XGBoost Evaluation ===

Confusion Matrix:
[[291   5]
 [ 23  17]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.98      0.95       296
           1       0.77      0.42      0.55        40

    accuracy                           0.92       336
   macro avg       0.85      0.70      0.75       336
weighted avg       0.91      0.92      0.91       336