In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('Feature_extracted_dataset(whd).csv')
df.head(10)

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
0,1313919,41,8,5993,Yes,1,6,19479,3,Nurse,2,4,0,5,2,0,1,11,Single,No
1,1200302,49,10,5130,No,8,10,24907,2,Other,2,7,1,7,3,1,3,23,Married,No
2,1060315,37,7,2090,Yes,2,0,2396,2,Nurse,1,0,0,0,4,0,3,15,Single,Yes
3,1272912,33,8,2909,Yes,3,8,23159,3,Other,1,7,3,0,4,0,3,11,Married,No
4,1414939,27,6,3468,No,2,2,16632,3,Nurse,1,2,2,2,1,1,3,12,Married,No
5,1633361,32,8,3068,No,2,7,11864,3,Nurse,1,7,3,6,4,0,2,13,Single,No
6,1329390,59,12,2670,Yes,3,1,9964,4,Nurse,1,0,0,0,3,3,2,20,Married,No
7,1699288,30,1,2693,No,24,1,13335,3,Nurse,1,0,0,0,4,1,3,22,Divorced,No
8,1469740,38,10,9526,No,23,9,8787,2,Therapist,3,7,1,8,4,0,3,21,Single,No
9,1101291,36,17,5237,No,27,7,16577,3,Nurse,2,7,7,7,3,2,2,13,Married,No

In [5]:
df = df.drop(columns=['EmployeeID'])
df

,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
0,41,8,5993,Yes,1,6,19479,3,Nurse,2,4,0,5,2,0,1,11,Single,No
1,49,10,5130,No,8,10,24907,2,Other,2,7,1,7,3,1,3,23,Married,No
2,37,7,2090,Yes,2,0,2396,2,Nurse,1,0,0,0,4,0,3,15,Single,Yes
3,33,8,2909,Yes,3,8,23159,3,Other,1,7,3,0,4,0,3,11,Married,No
4,27,6,3468,No,2,2,16632,3,Nurse,1,2,2,2,1,1,3,12,Married,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,26,1,2340,Yes,24,1,23213,1,Nurse,1,0,0,0,3,0,1,18,Single,Yes
1672,46,15,9071,Yes,10,3,11563,2,Nurse,3,2,1,2,3,1,3,19,Married,No
1673,20,1,2836,No,1,1,11757,2,Other,1,0,0,0,4,0,4,13,Single,No
1674,39,21,12742,No,1,21,7060,2,Therapist,4,6,11,8,4,1,3,16,Married,No
1675,27,9,6500,No,2,8,26997,4,Nurse,2,7,0,7,1,0,2,14,Single,No

In [6]:
cols = df.select_dtypes(include=["int64"]).columns
X = df[cols]
y = df["Attrition"]

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

In [8]:
print("Explained variance ratio:", pca.explained_variance_ratio_)
print("Total explained by 2 components:", pca.explained_variance_ratio_.sum())

Explained variance ratio: [0.30891769 0.10332995]
Total explained by 2 components: 0.41224764125478874

In [9]:
df_pca = pd.DataFrame(X_pca, columns=["PCA1","PCA2"])
df_out = pd.concat([df_pca, y.reset_index(drop=True)], axis=1)
df_out.head()

       PCA1      PCA2 Attrition
0 -0.362471 -0.368590        No
1  0.773117  0.087038        No
2 -2.383439 -0.551429       Yes
3 -0.926998  0.506276        No
4 -1.921956  0.339090        No